#!/usr/bin/env perl
#
# prune-bib.pl
#
# Build a bibliography containing only the entries the Springer volume actually
# cites. Run from the MAIN repository root (it reads the four source .bib files
# and the eleven chapters there):
#
#   perl springer/prune-bib.pl
#
# Writes springer/references-springer.bib. Copy that into the standalone folder
# as the volume's single bibliography, and point index.Rmd's `bibliography:`
# field at it. Rerun after any citation change.
#
# Two steps. First it collects every pandoc citation key in the chapters, taking
# care to skip fenced code, inline code, and bookdown's \@ref() syntax, which
# looks exactly like a citation to a naive regex. Then it walks the source .bib
# files with brace counting rather than line matching, so multi-line and nested
# entries survive intact, and emits the wanted subset plus any crossref targets.

use strict;
use warnings;

my $AT = chr(64);   # built from a char code so no shell can mangle it

my @CHAPTERS = qw(
  36-endogeneity.Rmd 37-biases.Rmd 38-dag.Rmd 39-controls.Rmd 40-report.Rmd
  41-EDA.Rmd 42-sensitivity-robustness.Rmd 42.5-placebo-falsification.Rmd
  42.6-publication-bias-phacking.Rmd 43-rep_synthetic_data.Rmd
  43.5-differential-privacy.Rmd 44-hpc.Rmd 45-clustered-inference.Rmd
);
my @BIBS = qw(book.bib packages.bib references.bib references1.bib);
my $OUT  = 'springer/references-springer.bib';

for my $f (@CHAPTERS, @BIBS) {
    die "cannot find $f. Run this from the main repository root.\n" unless -e $f;
}

# ---- 1. collect citation keys -------------------------------------------------
my %want;
for my $f (@CHAPTERS) {
    open my $fh, '<', $f or die "open $f: $!";
    my $inchunk = 0;
    while (my $l = <$fh>) {
        if ($l =~ /^```/) { $inchunk = !$inchunk; next }
        next if $inchunk;
        $l =~ s/`[^`]*`//g;
        while ($l =~ /(?<![\\w])\Q$AT\E(-?)([A-Za-z0-9_][A-Za-z0-9_:.+\/#\$%&?<>~-]*)/g) {
            my $k = $2;
            $k =~ s/[.,;:]+$//;
            next if $k eq 'ref';
            $want{$k} = 1;
        }
    }
    close $fh;
}

# ---- 2. parse the source bibliographies ---------------------------------------
my (%entry, %src, @order, @dups);
for my $bib (@BIBS) {
    open my $fh, '<', $bib or die "open $bib: $!";
    local $/;
    my $t = <$fh>;
    close $fh;
    while ($t =~ /\Q$AT\E([A-Za-z]+)\s*\{\s*([^,\s}]+)\s*,/g) {
        my ($type, $key) = ($1, $2);
        next if lc($type) =~ /^(comment|string|preamble)$/;
        my $start = $-[0];
        my $i     = index($t, '{', $start);
        my ($depth, $j) = (0, $i);
        while ($j < length $t) {
            my $c = substr($t, $j, 1);
            $depth++ if $c eq '{';
            if ($c eq '}') { $depth--; last if $depth == 0 }
            $j++;
        }
        if (exists $entry{$key}) { push @dups, "$key ($src{$key} and $bib)"; next }
        $entry{$key} = substr($t, $start, $j - $start + 1);
        $src{$key}   = $bib;
        push @order, $key;
    }
}

# ---- 3. pull in crossref targets, then write ----------------------------------
my %need = %want;
for my $k (keys %want) {
    next unless exists $entry{$k};
    while ($entry{$k} =~ /crossref\s*=\s*[{"]([^}"]+)[}"]/gi) { $need{$1} = 1 }
}
my @missing = sort grep { !exists $entry{$_} } keys %need;
my @found   = grep { $need{$_} && exists $entry{$_} } @order;

open my $out, '>', $OUT or die "write $OUT: $!";
print $out <<"HEAD";
% Bibliography for the Springer volume, Practical Issues in Data Analysis
% and Reporting. Generated by pruning the book's four .bib files down to
% the entries actually cited by the eleven chapters of this volume.
% Regenerate with springer/prune-bib.pl after any citation change.

HEAD
print $out $entry{$_}, "\n\n" for @found;
close $out;

printf "source entries : %d across %d files\n", scalar(keys %entry), scalar(@BIBS);
printf "cited keys     : %d\n", scalar(keys %need);
printf "written        : %d entries to %s\n", scalar(@found), $OUT;
if (@dups)    { print "duplicate keys : ", scalar(@dups), "\n"; print "  $_\n" for @dups }
if (@missing) { print "MISSING (cited but not in any .bib):\n"; print "  $_\n" for @missing; exit 1 }
print "all cited keys resolved\n";
