## Spline Regression

This chapter is based on [CMU stat](https://www.stat.cmu.edu/~ryantibs/advmethods/notes/smoothspline.pdf)  

Definition: a k-th order spline is a piecewise polynomial function of degree k, that is continuous and has continuous derivatives of orders 1,..., k -1, at its knot points   

Equivalently, a function f is a k-th order spline with knot points at $t_1 < ...< t_m$ if  

 * f is a polynomial of degree k on each of the intervals $(-\infty, t_1], [t_1,t_2],...,[t_m, \infty)$  
 * $f^{(j)}$, the j-th derivative of f, is continuous at $t_1,...,t_m$ for each j = 0,1,...,k-1

A common case is when k = 3, called cubic splines. (piecewise cubic functions are continuous, and also continuous at its first and second derivatives)  

To parameterize the set of splines, we could use **truncated power basis**, defined as  

$$
g_1(x) = 1 \\
g_2(x) = x \\
... \\
g_{k+1}(x) = x^k \\
g_{k+1+j}(x) = (x-t_j)^k_+
$$

where j = 1,...,m and $x_+$ = max{x,0}  

However, now software typically use B-spline basis.  

Regression splines are funcitons of 

