# Imputation (Missing Data)

Imputation is usually seen as the illegitimate child of statistical analysis. Several reasons that contribute to this negative views could be:  

 (1) Peopled hardly do imputation correctly
 (2) Imputation can only be applied to a small range of problems correctly
 
If you have missing data on y (dependent variable), you probability would not be able to do any imputation appropriately. However, if you have certain type of missing data (e.g., non-random missing data) in the xs variable (independent variables), then you can still salvage your collected data points with imputation.  

We also need to talk why you would want to do imputation in the first place. If your purpose is inference/ explanation (valid statistical inference not optimal point prediction), then imputation would not offer much help [@Rubin_1996]. However, if your purpose is prediction, you would want your standard error to be reduced by including information (non-missing data) on other variables of a data point. Then imputation could be the tool that you're looking for.


For most software packages, it will use listwise deletion or casewise deletion to have complete case analysis (analysis with only observations with all information). Not until recently that statistician can propose some methods that are a bit better than listwise deletion which are maximum likelihood and multiple imputation. 

## Assumptions 

### Missing Completely at Random (MCAR)
The probability of missing data on a variable is unrelated to the value of it or to the values of any other variables in the data set. 

**Note**: the "missingness" on Y can be correlated with the "missingness" on X 
We can compare the value of other variables for the observations with missing data, and observations without missing data. If we reject the t-test for mean difference, we can say there is evidence that the data are not MCAR. But we cannot say that our data are MCAR if we fail to reject the t-test. 

### Missing at Random (MAR)
MAR is weaker than MCAR

$$
P(Y_{missing}|Y,X)= P(Y_{missing}|X)
$$
The probability of Y missing given Y and X equal to the probability of of Y missing given X. 
However, it is impossible to provide evidence to the MAR condition. 

### Ignorable
The missing data mechanism is ignorable when 

 (1) The data are MAR
 (2) the parameters in the function of the missing data process are unrelated to the parameters (of interest) that need to be estimated. 
 
 In this case, you actually don't need to model the missing data mechanisms unless you would like to improve on your accuracy, in which case you still need to be very rigorous about your approach to improve efficiency in your parameters. 
 
### Nonignorable
Hence, in the case of nonignorable, the data are not MAR. Then, your parameters of interest will be biased if you do not model the missing data mechanism. 
One of the most widely used approach for nonignorable missing data is [@Heckman_1976]


## Solutions to Missing data
### Listwise Deletion

Advantages: 

 * Can be applied to any statistical test (SEM, multi-level regression, etc.)
 * In the case of MCAR, both the parameters estimates and its standard errors are unbiased. 
 * In the case of MAR among independent variables (not depend on the values of dependent variables), then listwise deletion parameter estimates can still be unbiased. [@Little_1992] For example, you have a model $y=\beta_{0}+\beta_1X_1 + \beta_2X_2 +\epsilon$ if the probability of missing data on X1 is independent of Y, but dependent on the value of X1 and X2, then the model estimates are still unbiased.  
    + The missing data mechanism the depends on the values of the independent variables are the same as stratified sampling. And stratified sampling does not bias your estimates 
    + In the case of logistic regression, if the probability of missing data on any variable depends on the value of the dependent variable, but independent of the value of the independent variables, then the listwise deletion will yield biased intercept estimate, but consistent estimates of the slope and their standard errors [@Vach_1994]. However, logistic regression will still fail if the probability of missing data is dependent on both the value of the dependent and independent variables.
    + Under regression analysis, listwise deletion is more robust than maximum likelihood and multiple imputation when MAR assumption is violated. 

Disadvantages: 

 * It will yield a larger standard errors than other more sophisticated methods discussed later. 
 * If the data are not MCAR, but MAR, then your listwise deletion can yield biased estimates. 
 * In other cases than regression analysis, other sophisticated methods can yield better estimates compared to listwise deletion. 

### Pairwise Deletion
This method could only be used in the case of linear models such as linear regression, factor analysis, or SEM. 
The premise of this method based on that the coefficient estimates are calculated based on the means, standard deviations, and correlation matrix. Compared to listwise deletion, we still utilized as many correlation between variables as possible to compute the correlation matrix. 

Advantages: 

 * If the true missing data mechanism is MCAR, pair wise deletion will yield consistent estimates, and unbiased in large samples 
 * Compared to listwise deletion: [@Glasser_1964]
    + If the correlation among variables are low, pairwise deletion is more efficient estimates than listwise
    + If the correlations among variables are high, listwise deletion is more efficient than pairwise. 
 
Disadvantages:

 * If the data mechanism is MAR, pairwise deletion will yield biased estimates. 
 * In small sample, sometimes covariance matrix might not be positive definite, which means coefficients estimates cannot be calculated. 


**Note**: You need to read carefully on how your software specify the sample size because it will alter the standard errors.

### Dummy Variable Adjustment 

Also known as Missing Indicator Method or Proxy Variable

Add another variable in the database to indicate whether a value is missing. 


Create 2 variables

\begin{equation}
D=
\begin{cases}
1 & \text{data on X are missing} \\
0 & \text{otherwise}\\
\end{cases}
\end{equation}

\begin{equation}
X^* = 
\begin{cases}
X & \text{data are available} \\
c & \text{data are missing}\\
\end{cases}
\end{equation}

**Note**: A typical choice for c is usually the mean of X

Interpretation:

 * Coefficient of D is the the difference in the expected value of Y between the group with data and the group without data on X.
 * Coefficient of X* is the effect of the group with data on Y


Disadvantages:

 * This method yields bias estimates of the coefficient even in the case of MCAR [@Jones_1996]

### Imputation

#### Maximum Likelihood
When missing data are MAR and monotonic (such as in the case of panel studies), ML can be adequately in estimating coefficients. 

Monotonic means that if you are missing data on X1, then that observation also has missing data on all other variables that come after it. 

ML can generally handle linear models, log-linear model, but beyond that, ML still lacks both theory and software to implement.

##### Expectation-Maximization Algorithm (EM Algorithm)

An iterative process:  

(1) Other variables are used to impute a value (Expectation).  
(2) Check whether the value is most likely (Maximization).  
(3) If not, it re-imputes a more likely value.  

You start your regression with your estimates based on either listwise deletion or pairwise deletion.
After regressing missing variables on available variables, you obtain a regression model.
Plug the missing data back into the original model, with modified variances and covariances For example, if you have missing data on $X_{ij}$ you would regress it on available data of $X_{i(j)}$, then plug the expected value of $X_{ij}$ back with its $X_{ij}^2$ turn into $X_{ij}^2 + s_{j(j)}^2$ where $s_{j(j)}^2$ stands for the residual variance from regressing $X_{ij}$ on $X_{i(j)}$
With the new estimated model, you rerun the process until the estimates converge.


Advantages: 

 (1) easy to use
 (2) preserves the relationship with other variables
 
Disadvantages:

 (1) Standard errors of the coefficients are incorrect (biased usually downward)
 (2) Models with overidentification, the estimates will not be efficient. 
 
 
 



##### Direct ML (raw maximum likelihood)


Advantages 

 (1) efficient estimates and correct standard errors.

Disadvantages:

 (1) Hard to implements
 
 
 
 
#### Multiple Imputation
MI is designed to use "the Bayesian model-based approach to *create* procedures, and the frequentist (randomization-based approach) to *evaluate* procedures". [@Rubin_1996]


MI estimates have the same properties as [ML][Maximum Likelihood] when the data is [MAR][Missing at Random (MAR)]

 * Consistent
 * Asymptotically efficient
 * Asymptotically normal

MI can be applied to any type of model, unlike [Maximum Likelihood] that is only limited to a small set of models.

A drawback of MI is that it will produce slightly different estimates every time you run it. To avoid such problem, you can set seed when doing your analysis to ensure its reproducibility.

##### Single Random Imputaiton 
Random draws form the residual distribution of each imputed variable and add those random numbers to the imputed values.  

For example, if we have missing data on X, and it's MCAR, then  

 (1) regress X on Y ([Listwise Deletion] method) to get its residual distribution. 
 (2) For every missing value on X, we substitute with $\tilde{x_i}=\hat{x_i} + \rho u_i$ where 
     + $u_i$ is a random draw from a standard normal distribution
     + $x_i$ is the predicted value from the regression of X and Y
     + $\rho$ is the standard deviation of the residual distribution of X regressed on Y.

However, the model you run with the imputed data still thinks that your data are collected, not imputed, which leads your standard error estimates to be too low and test statistics too high.  

To address this problem, we need to repeat the imputation process which leads us to repeated imputation or multiple random imputation. 

##### Repeated Imputation
"Repeated imputations are draws from the posterior predictive distribution of the missing values under a specific model , a particular Bayesian model for both the data and the missing mechanism".[@Rubin_1996]

Repeated imputation, also known as, multiple random imputation, allows us to have multiple "completed" data sets. The variability across imputations will adjust the standard errors upward. 

#### Mean, Mode, Median Imputation

 * Bad:  
 
    + Mean imputation does not preserve the relationships among variables   
    + Mean imputation leads to An Underestimate of Standard Errors → you’re making Type I errors without realizing it.
    + Biased estimates of variances and covariances [@Haitovsky_1968]
 
#### Hot Deck Imputation

Randomly choose value from other observations that share similar values on other variables.  

 * Good:  
    - Constrained to only possible values.  
    - Since the value is picked at random, it adds some variability, which might come in handy when calculating standard errors.  
 
#### Cold Deck Imputation  

Contrary to Hot Deck, Cold Deck choose value systematically from an observation that has similar values on other variables, which remove the random variation that we want.  

#### Regression Imputation  

Also known as conditional mean imputation
Missing value is based (regress) on other variables.  

 * Good:  
 
    - Maintain the relationship with other variables  
    - If the data are MCAR, least-squares coefficients estimates will be consistent, and approximately unbiased in large samples [@Gourieroux_1981]
        + Can have improvement on efficiency by using weighted least squares [@Beale_1975] or generalized least squares [@Gourieroux_1981].

 * Bad:  
 
    - No variability left.  treated data as if they were collected. 
    - Underestimate the standard errors and overestimate test statistics
    
    
#### Stochatistc Imputation  

`Regression imputation + random residual = Stochastic Imputation`

Most multiple imputation is based off of some form of stochastic regression imputation.  

#### Interpolation and Extrapolation  

An estimated value from other observations from the same individual. It usually only works in longitudinal data.  



#### K-nearest neighbour (KNN) imputation  

The above methods are model-based imputation (regression).  
This is an example of neighbor-based imputation (K-nearest neighbor).  

For a discrete variable, it uses the most frequent value among the k nearest neighbors. 

 * Distance metrics: Hamming distance.  
 
For a continuous variable, it uses the mean or mode.  

 * Distance metrics:  
    - Euclidean  
    - Mahalanobis  
    - Manhattan  
    
#### Bayesian Ridge regression implementation  




### Criteria for Choosing an Effective Approach

Criteria for an ideal technique in treating missing data:  

1. Unbiased parameter estimates
2. Adequate power
3. Accurate standard errors (p-values, confidence intervals)

The Multiple Imputation and Full Information Maximum Likelihood are the the most ideal candidate. Single imputation will generally lead to underestimation of standard errors.



### Another Perspective  

In the imputation world, you can go for either single or multiple imputation.  
Most of the imputation methods listed above are single imputation. A downfall of single imputation is its underestimation towards standard error.

<br>
Model bias can arisen from various factors including:  
 
 * Imputation method  
 * Missing data mechanism (MCAR vs. MAR)  
 * Proportion of the missing data  
 * Information available in the data set  
 
 

Since the imputed observations are themselves estimates, their values have corresponding random error. But when you put in that estimate as a data point, your software doesn’t know that. So it overlooks the extra source of error, resulting in too-small standard errors and too-small p-values.
So multiple imputation comes up with multiple estimates. Two of the methods listed above work as the imputation method in multiple imputation–hot deck and stochastic regression.
Because these two methods have a random component, the multiple estimates are slightly different. This re-introduces some variation that your software can incorporate in order to give your model accurate estimates of standard error.
Multiple imputation was a huge breakthrough in statistics about 20 years ago. It solves a lot of problems with missing data (though, unfortunately not all) and if done well, leads to unbiased parameter estimates and accurate standard errors.
If your rate of missing data is very, very small, it honestly doesn’t matter what technique you use. I’m talking very, very, very small (2-3%).

Missing Data Mechanisms
(1)	Missing Completely at Random (MCAR)
-	the propensity for a data point to be missing is completely random.
-	There’s no relationship between whether a data point is missing and any values in the data set, missing or observed.
-	The missing data are just a random subset of the data.
(2)	Missing at Random. (MAR)
-	the propensity for a data point to be missing is not related to the missing data, but it is related to some of the observed data. In another word, there is a systematic relationship between the propensity of missing values and the observed data, but not the missing data.
- For example, if men are more likely to tell you their weight than women, weight is MAR
-	MAR requires that the cause of the missing data is unrelated to the missing values but may be related to the observed values of other variables.
-	MAR means that the missing values are related to observed values on other variables. As an example of CD missing data, missing income data may be unrelated to the actual income values but are related to education. Perhaps people with more education are less likely to reveal their income than those with less education
(3)	Non-Ignorable (NI)
- Another name: Missing Not at Random (MNAR): there is a relationship between the propensity of a value to be missing and its values
- For example, people with low education will be less likely to report it.
- We need to model why the data are missing and what the likely values are. 
-	the missing data mechanism is related to the missing values
-	It commonly occurs when people do not want to reveal something very personal or unpopular about themselves
-	Complete case analysis can give highly biased results for NI missing data. If proportionally more low and moderate income individuals are left in the sample because high income people are missing, an estimate of the mean income will be lower than the actual population mean.



Remember that there are three goals of multiple imputation, or any missing data technique: Unbiased parameter estimates in the final analysis (regression coefficients, group means, odds ratios, etc.); accurate standard errors of those parameter estimates, and therefore, accurate p-values in the analysis; and adequate power to find meaningful parameter values significant.
1. Don’t round off imputations for dummy variables. Many common imputation techniques, like MCMC, require normally distributed variables. Suggestions for imputing categorical variables were to dummy code them, impute them, then round off imputed values to 0 or 1. Recent research, however, has found that rounding off imputed values actually leads to biased parameter estimates in the analysis model. You actually get better results by leaving the imputed values at impossible values, even though it’s counter-intuitive.

2. Don’t transform skewed variables. Likewise, when you transform a variable to meet normality assumptions before imputing, you not only are changing the distribution of that variable but the relationship between that variable and the others you use to impute. Doing so can lead to imputing outliers, creating more bias than just imputing the skewed variable.

3. Use more imputations. The advice for years has been that 5-10 imputations are adequate. And while this is true for unbiasedness, you can get inconsistent results if you run the multiple imputation more than once. Bodner (2008) recommends having as many imputations as the percentage of missing data. Since running more imputations isn’t any more work for the data analyst, there’s no reason not to.
Bodner, T. E. 2008. “What Improves with Increased Missing Data Imputations?”
Structural Equation Modeling 15(4):651–75.
4. Create multiplicative terms before imputing. When the analysis model contains a multiplicative term, like an interaction term or a quadratic, create the multiplicative terms first, then impute. Imputing first, and then creating the multiplicative terms actually biases the regression parameters of the multiplicative term (von Hippel, 2009).
von Hippel, P.T. (2009). “How To Impute Squares, Interactions, and Other Transformed Variables.” Sociological Methodology 39.
1.	Alternatives to multiple imputation aren’t usually better. Multiple imputation assumes the data are missing at random. In most tests, if an assumption is not met, there are better alternatives—a nonparametric test or an alternative type of model. This is often not true with missing data. Alternatives like listwise deletion (a.k.a. ignoring it) have more stringent assumptions. So do nonignorable missing data techniques like Heckman’s selection models.


Do not use these ad-hoc: 
Pairwise Deletion: use the available data for each part of an analysis.  This has been shown to result in correlations beyond the 0,1 range and other fun statistical impossibilities.
Mean Imputation: substitute the mean of the observed values for all missing data.  There are so many problems, it’s difficult to list them all, but suffice it to say, this technique never meets the above 3 criteria.
Dummy Variable: create a dummy variable that indicates whether a data point is missing, then substitute any arbitrary value for the missing data in the original variable.  Use both variables in the analysis.  While it does help the loss of power, it usually leads to biased results.

Multiple Imputation of categorical variables is bad 
Paul Allison, one of my favorite authors of statistical information for researchers, did a study that showed that the most common method actually gives worse results that listwise deletion.  (Did I mention I’ve used it myself?)
What is the bad method?
1. Dummy code the variable
2. Impute a continuous value.  This will generally be between 0 and 1.
3. Round off to either 0 or 1, based on whether the imputed value is below or above .5.
As Allison discovered, this method generally leads to biased results, and incorrect standard errors
What to do instead?
Allison compared this approach to four others, each of which generally gave more accurate results, at least under some conditions.
1. Listwise deletion
2. Imputation of the continuous variable without rounding (just leave off step 3).
3. Logistic Regression imputation
4. Discriminant Analysis imputation
These last two generally performed best, but only work in limited situations.




How to Diagnose the Missing Data Mechanism
by Karen Grace-Martin 4 Comments

One important consideration in choosing a missing data approach is the missing data mechanism—different approaches have different assumptions about the mechanism.

Each of the three mechanisms describes one possible relationship between the propensity of data to be missing and values of the data, both missing and observed.

The Missing Data Mechanisms
Missing Completely at Random, MCAR, means there is no relationship between the missingness of the data and any values, observed or missing. Those missing data points are a random subset of the data. There is nothing systematic going on that makes some data more likely to be missing than others.

Missing at Random, MAR, means there is a systematic relationship between the propensity of missing values and the observed data, but not the missing data.

Whether an observation is missing has nothing to do with the missing values, but it does have to do with the values of an individual’s observed variables. So, for example, if men are more likely to tell you their weight than women, weight is MAR.

Missing Not at Random, MNAR, means there is a relationship between the propensity of a value to be missing and its values. This is a case where the people with the lowest education are missing on education or the sickest people are most likely to drop out of the study.

MNAR is called “non-ignorable” because the missing data mechanism itself has to be modeled as you deal with the missing data. You have to include some model for why the data are missing and what the likely values are.

“Missing Completely at Random” and “Missing at Random” are both considered ‘ignorable’ because we don’t have to include any information about the missing data itself when we deal with the missing data.

Why you need to know the mechanism you have
Multiple imputation and Maximum Likelihood assume the data are at least missing at random. So the important distinction here is whether the data are MAR as opposed to MNAR.

Listwise deletion, however, requires the data are MCAR in order to not introduce bias in the results.

As long as the distribution and percentage of missing data is no so great that it negatively affects power, listwise deletion can be a good choice for MCAR missing data. So the important distinction here is whether the data are MCAR as opposed to MAR.

Keep in mind that in most data sets, more than one variable will have missing data, and they may not all have the same mechanism. It’s worthwhile diagnosing the mechanism for each variable with missing data before choosing an approach.

I use the term diagnosing rather than testing, because you’re not going to get a straight answer without knowing the values of the missing data. Of course, if you knew those, you wouldn’t be doing any of this.

It’s like checking for multicollinearity or testing assumptions. Each piece of information tells you something, but there is no definitive answer.

You have to get at the mechanism in a number of ways and then decide if making the assumption about the mechanism is reasonable.


##### Diagnosing the Mechanism
1. MAR vs. MNAR
The only true way to distinguish between MNAR and MAR is to measure some of that missing data. It’s a common practice among professional surveyors to, for example, follow-up on a paper survey with phone calls to a group of the non-respondents and ask a few key survey items. This allows you to compare respondents to non-respondents.

If their responses on those key items differ by very much, that’s good evidence that the data are MNAR.

However in most missing data situations, we don’t have the luxury of getting a hold of the missing data. So while we can’t test it directly, we can examine patterns in the data get an idea of what’s the most likely mechanism.

The first thing in diagnosing randomness of the missing data is to use your substantive scientific knowledge of the data and your field. The more sensitive the issue, the less likely people are to tell you. They’re not going to tell you as much about their cocaine usage as they are about their phone usage.

Likewise, many fields have common research situations in which non-ignorable data is common. Educate yourself in your field’s literature.

2. MCAR vs. MAR
There is a very useful test for MCAR, Little’s test.

A second technique is to create dummy variables for whether a variable is missing.

1 = missing
0 = observed

You can then run t-tests and chi-square tests between this variable and other variables in the data set to see if the missingness on this variable is related to the values of other variables.

For example, if women really are less likely to tell you their weight than men, a chi-square test will tell you that the percentage of missing data on the weight variable is higher for women than men.



"Judging the quality of missing data procedures by their ability to recreate the individual missing values (according to hit rate, mean square error, etc) does not lead to choosing procedures that result in valid inference", [@Rubin_1996]