# Causality 
After all of the mumbo jumbo that we have learned so far, I want to now talk about the concept of causality.  
We usually say that correlation is not causation. Then, what is causation?  
One of my favorite books has explained this concept beautifully [@Pearl_2018]. And I am just going to quickly summarize the gist of it from my understanding. I hope that it can give you an initial grasp on the concept so that later you can continue to read up and develop a deeper understanding. 


It's important to have a deep understanding regarding the method research. However, one needs to be aware of its limitation and compliment with conceptual understanding. The aspect of concepts is typically referred in statistics when as expert knowledge. As mentioned in various sections throughout the book, we see that we need to ask experts for number as our baseline or visit literature to gain insight from past research.  

Here, we dive in a more conceptual side statistical analysis as a whole, regardless of particular approach. 