---
title: "Appendix"
author: "Mike"
date: "11/11/2020"
output: html_document
---

# Appendix
## Short-cut
These are shortcuts that you probably you remember when working with R. Even though it might take a bit of time to learn and use them as your second nature, but they will save you a lot of time.\
Just like learning another language, the more you speak and practice it, the more comfortable you are speaking it. \

function|short-cut
---|---
navigate folders in console|`" " + tab`
pull up short-cut cheat sheet | `ctrl + shift + k`
go to file/function\ (everything in your project) | `ctrl + .`
search everything | `cmd + shift + f`
navigate between tabs | `Crtl + shift + .`
type function faster | `snip + shift + tab`
type faster | `use tab for fuzzy match`
| `cmd + up`
|`ctrl + .`


## Function short-cut
apply one function to your data to create a new variable:
`mutate(mod=map(data,function))`\
instead of using `i in 1:length(object)`:
`for (i in seq_along(object))`\
apply multiple function:
`map_dbl`\
apply multiple function to multiple variables:`map2`  
`autoplot(data)`  plot times series data  
`mod_tidy = linear(reg) %>% set_engine('lm') %>% fit(price ~ ., data=data)` fit lm model. It could also fit other models (stan, spark, glmnet, keras)  


 * Sometimes, data-masking will not be able to recognize whether you're calling from environment or data variables. To bypass this, we use `.data$variable` or `.env$variable`. For example `data %>% mutate(x=.env$variable/.data$variable`

## Citation

include a citation by `[@Farjam_2015]`  

cite packages used in this session

`package=ls(sessionInfo()$loadedOnly) for (i in package){print(toBibtex(citation(i)))}`
```{r, eval=FALSE}
package=ls(sessionInfo()$loadedOnly) 
for (i in package){
    print(toBibtex(citation(i)))
    }
```




