---
title: "Appendix"
author: "Mike"
date: "11/11/2020"
output: html_document
---

# Appendix
## Short-cut
These are shortcuts that you probably you remember when working with R. Even though it might take a bit of time to learn and use them as your second nature, but they will save you a lot of time.\
Just like learning another language, the more you speak and practice it, the more comfortable you are speaking it. \

function|short-cut
---|---
navigate folders in console|`" " + tab`
pull up short-cut cheat sheet | `ctrl + shift + k`
go to file/function\ (everything in your project) | `ctrl + .`
search everything | `cmd + shift + f`
navigate between tabs | `Crtl + shift + .`
type function faster | `snip + shift + tab`
type faster | `use tab for fuzzy match`
| `cmd + up`
|`ctrl + .`


## Function short-cut
apply one function to your data to create a new variable:
`mutate(mod=map(data,function))`\
instead of using `i in 1:length(object)`:
`for (i in seq_along(object))`\
apply multiple function:
`map_dbl`\
apply multiple function to multiple variables:`map2`

