<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 9 Nonlinear and Generalized Linear Mixed Models | A Guide on Data Analysis</title>
<meta name="author" content="Mike Nguyen">
<meta name="description" content="NLMMs extend the nonlinear model to include both fixed effects and random effects GLMMs extend the generalized linear model to include both fixed effects and random effects. A nonlinear mixed...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 9 Nonlinear and Generalized Linear Mixed Models | A Guide on Data Analysis">
<meta property="og:type" content="book">
<meta property="og:image" content="/images/cover.jpg">
<meta property="og:description" content="NLMMs extend the nonlinear model to include both fixed effects and random effects GLMMs extend the generalized linear model to include both fixed effects and random effects. A nonlinear mixed...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 9 Nonlinear and Generalized Linear Mixed Models | A Guide on Data Analysis">
<meta name="twitter:description" content="NLMMs extend the nonlinear model to include both fixed effects and random effects GLMMs extend the generalized linear model to include both fixed effects and random effects. A nonlinear mixed...">
<meta name="twitter:image" content="/images/cover.jpg">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script><script src="libs/proj4js-2.3.15/proj4.js"></script><link href="libs/highcharts-8.1.2/css/motion.css" rel="stylesheet">
<script src="libs/highcharts-8.1.2/highcharts.js"></script><script src="libs/highcharts-8.1.2/highcharts-3d.js"></script><script src="libs/highcharts-8.1.2/highcharts-more.js"></script><script src="libs/highcharts-8.1.2/modules/stock.js"></script><script src="libs/highcharts-8.1.2/modules/map.js"></script><script src="libs/highcharts-8.1.2/modules/annotations.js"></script><script src="libs/highcharts-8.1.2/modules/data.js"></script><script src="libs/highcharts-8.1.2/modules/drilldown.js"></script><script src="libs/highcharts-8.1.2/modules/item-series.js"></script><script src="libs/highcharts-8.1.2/modules/offline-exporting.js"></script><script src="libs/highcharts-8.1.2/modules/overlapping-datalabels.js"></script><script src="libs/highcharts-8.1.2/modules/exporting.js"></script><script src="libs/highcharts-8.1.2/modules/export-data.js"></script><script src="libs/highcharts-8.1.2/modules/funnel.js"></script><script src="libs/highcharts-8.1.2/modules/heatmap.js"></script><script src="libs/highcharts-8.1.2/modules/treemap.js"></script><script src="libs/highcharts-8.1.2/modules/sankey.js"></script><script src="libs/highcharts-8.1.2/modules/dependency-wheel.js"></script><script src="libs/highcharts-8.1.2/modules/organization.js"></script><script src="libs/highcharts-8.1.2/modules/solid-gauge.js"></script><script src="libs/highcharts-8.1.2/modules/streamgraph.js"></script><script src="libs/highcharts-8.1.2/modules/sunburst.js"></script><script src="libs/highcharts-8.1.2/modules/vector.js"></script><script src="libs/highcharts-8.1.2/modules/wordcloud.js"></script><script src="libs/highcharts-8.1.2/modules/xrange.js"></script><script src="libs/highcharts-8.1.2/modules/tilemap.js"></script><script src="libs/highcharts-8.1.2/modules/venn.js"></script><script src="libs/highcharts-8.1.2/modules/gantt.js"></script><script src="libs/highcharts-8.1.2/modules/timeline.js"></script><script src="libs/highcharts-8.1.2/modules/parallel-coordinates.js"></script><script src="libs/highcharts-8.1.2/modules/bullet.js"></script><script src="libs/highcharts-8.1.2/modules/coloraxis.js"></script><script src="libs/highcharts-8.1.2/modules/dumbbell.js"></script><script src="libs/highcharts-8.1.2/modules/lollipop.js"></script><script src="libs/highcharts-8.1.2/modules/series-label.js"></script><script src="libs/highcharts-8.1.2/plugins/motion.js"></script><script src="libs/highcharts-8.1.2/custom/reset.js"></script><script src="libs/highcharts-8.1.2/modules/boost.js"></script><script src="libs/highchart-binding-0.8.2/highchart.js"></script><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){window.dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-DMNX2X65HQ');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS -->
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">A Guide on Data Analysis</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li><a class="" href="introduction.html"><span class="header-section-number">1</span> Introduction</a></li>
<li><a class="" href="prerequisites.html"><span class="header-section-number">2</span> Prerequisites</a></li>
<li class="book-part">BASIC</li>
<li><a class="" href="descriptive-stat.html"><span class="header-section-number">3</span> Descriptive Statistics</a></li>
<li><a class="" href="basic-statistical-inference.html"><span class="header-section-number">4</span> Basic Statistical Inference</a></li>
<li class="book-part">REGRESSION</li>
<li><a class="" href="linear-regression.html"><span class="header-section-number">5</span> Linear Regression</a></li>
<li><a class="" href="non-linear-regression.html"><span class="header-section-number">6</span> Non-linear Regression</a></li>
<li><a class="" href="generalized-linear-models.html"><span class="header-section-number">7</span> Generalized Linear Models</a></li>
<li><a class="" href="linear-mixed-models.html"><span class="header-section-number">8</span> Linear Mixed Models</a></li>
<li><a class="active" href="nonlinear-and-generalized-linear-mixed-models.html"><span class="header-section-number">9</span> Nonlinear and Generalized Linear Mixed Models</a></li>
<li class="book-part">RAMIFICATIONS</li>
<li><a class="" href="model-specification.html"><span class="header-section-number">10</span> Model Specification</a></li>
<li><a class="" href="imputation-missing-data.html"><span class="header-section-number">11</span> Imputation (Missing Data)</a></li>
<li><a class="" href="data.html"><span class="header-section-number">12</span> Data</a></li>
<li><a class="" href="hypothesis-testing.html"><span class="header-section-number">13</span> Hypothesis Testing</a></li>
<li><a class="" href="prediction-and-estimation.html"><span class="header-section-number">14</span> Prediction and Estimation</a></li>
<li class="book-part">EXPERIMENTAL DESIGN</li>
<li><a class="" href="sampling.html"><span class="header-section-number">15</span> Sampling</a></li>
<li><a class="" href="analysis-of-variance-anova.html"><span class="header-section-number">16</span> Analysis of Variance (ANOVA)</a></li>
<li><a class="" href="multivariate-methods.html"><span class="header-section-number">17</span> Multivariate Methods</a></li>
<li class="book-part">CAUSAL INFERENCE</li>
<li><a class="" href="causal-inference.html"><span class="header-section-number">18</span> Causal Inference</a></li>
<li><a class="" href="experimental-design.html"><span class="header-section-number">19</span> Experimental Design</a></li>
<li><a class="" href="quasi-experimental.html"><span class="header-section-number">20</span> Quasi-experimental</a></li>
<li><a class="" href="endogeneity.html"><span class="header-section-number">21</span> Endogeneity</a></li>
<li><a class="" href="mediation.html"><span class="header-section-number">22</span> Mediation</a></li>
<li class="book-part">MISCELLANEOUS</li>
<li><a class="" href="report.html"><span class="header-section-number">23</span> Report</a></li>
<li class="book-part">APPENDIX</li>
<li><a class="" href="appendix.html"><span class="header-section-number">A</span> Appendix</a></li>
<li><a class="" href="bookdown-cheat-sheet.html"><span class="header-section-number">B</span> Bookdown cheat sheet</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/mikenguyen13/data_analysis">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="nonlinear-and-generalized-linear-mixed-models" class="section level1" number="9">
<h1>
<span class="header-section-number">9</span> Nonlinear and Generalized Linear Mixed Models<a class="anchor" aria-label="anchor" href="#nonlinear-and-generalized-linear-mixed-models"><i class="fas fa-link"></i></a>
</h1>
<ul>
<li>NLMMs extend the nonlinear model to include both fixed effects and random effects</li>
<li>GLMMs extend the generalized linear model to include both fixed effects and random effects.</li>
</ul>
<p>A nonlinear mixed model has the form of</p>
<p><span class="math display">\[
Y_{ij} = f(\mathbf{x_{ij} , \theta, \alpha_i}) + \epsilon_{ij}
\]</span></p>
<p>for the j-th response from cluster (or sujbect) i (<span class="math inline">\(i = 1,...,n\)</span>), where</p>
<ul>
<li><span class="math inline">\(j = 1,...,n_i\)</span></li>
<li>
<span class="math inline">\(\mathbf{\theta}\)</span> are the fixed effects</li>
<li>
<span class="math inline">\(\mathbf{\alpha}_i\)</span> are the random effects for cluster i</li>
<li>
<span class="math inline">\(\mathbf{x}_{ij}\)</span> are the regressors or design variables</li>
<li>
<span class="math inline">\(f(.)\)</span> is nonlinear mean response function</li>
</ul>
<p>A GLMM can be written as:</p>
<p>we assume</p>
<p><span class="math display">\[
y_i |\alpha_i \sim \text{indep } f(y_i | \alpha)
\]</span></p>
<p>and <span class="math inline">\(f(y_i | \mathbf{\alpha})\)</span> is an exponential family distribution,</p>
<p><span class="math display">\[
f(y_i | \alpha) = \exp [\frac{y_i \theta_i - b(\theta_i)}{a(\phi)} - c(y_i, \phi)]
\]</span></p>
<p>The conditional mean of <span class="math inline">\(y_i\)</span> is related to <span class="math inline">\(\theta_i\)</span></p>
<p><span class="math display">\[
\mu_i = \frac{\partial b(\theta_i)}{\partial \theta_i}
\]</span></p>
<p>The transformation of this mean will give us the desired linear model to model both the fixed and random effects.</p>
<p><span class="math display">\[
E(y_i |\alpha) = \mu_i \\
g(\mu_i) = \mathbf{x_i' \beta + z'_i \alpha}
\]</span></p>
<p>where <span class="math inline">\(g()\)</span> is a known link function and <span class="math inline">\(\mu_i\)</span> is the conditional mean. We can see similarity to <a href="generalized-linear-models.html#generalized-linear-models">GLM</a></p>
<p>We also have to specify the random effects distribution</p>
<p><span class="math display">\[
\alpha \sim f(\alpha)
\]</span></p>
<p>which is similar to the specification for mixed models.</p>
<p>Moreover, law of large number applies to fixed effects so that you know it is a normal distribution. But here, you can specify <span class="math inline">\(\alpha\)</span> subjectively.</p>
<p>Hence, we can show NLMM is a special case of the GLMM</p>
<p><span class="math display">\[
\mathbf{Y}_i = \mathbf{f}(\mathbf{x}_i, \mathbf{\theta, \alpha}_i) + \mathbf{\epsilon}_i \\
\mathbf{Y}_i = \mathbf{g}^{-1} (\mathbf{x}_i' \beta + \mathbf{z}_i' \mathbf{\alpha}_i) + \mathbf{\epsilon}_i
\]</span></p>
<p>where the inverse link function corresponds to a nonlinear transformation of the fixed and random effects.</p>
<p>Note:</p>
<ul>
<li>we can’t derive the analytical formulation of the marginal distribution because nonlinear combination of normal variables is not normally distributed, even in the case of additive error (<span class="math inline">\(e_i\)</span>) and random effects (<span class="math inline">\(\alpha_i\)</span>) are both normal.</li>
</ul>
<p><strong>Consequences of having random effects</strong></p>
<p>The marginal mean of <span class="math inline">\(y_i\)</span> is</p>
<p><span class="math display">\[
E(y_i) = E_\alpha(E(y_i | \alpha)) = E_\alpha (\mu_i) = E(g^{-1}(\mathbf{x_i' \beta + z_i' \alpha}))
\]</span></p>
<p>Because <span class="math inline">\(g^{-1}()\)</span> is nonlinear, this is the most simplified version we can go for.</p>
<p>In special cases such as log link (<span class="math inline">\(g(\mu) = \log \mu\)</span> or <span class="math inline">\(g^{-1}() = \exp()\)</span>) then</p>
<p><span class="math display">\[
E(y_i) = E(\exp(\mathbf{x_i' \beta + z_i' \alpha})) = \exp(\mathbf{x'_i \beta})E(\exp(\mathbf{z}_i'\alpha))
\]</span></p>
<p>which is the moment generating function of <span class="math inline">\(\alpha\)</span> evaluated at <span class="math inline">\(\mathbf{z}_i\)</span></p>
<p><br></p>
<p><strong>Marginal variance</strong> of <span class="math inline">\(y_i\)</span></p>
<p><span class="math display">\[
\begin{aligned}
var(y_i) &amp;= var_\alpha (E(y_i | \alpha)) + E_\alpha (var(y_i | \alpha)) \\
&amp;= var(\mu_i) + E(a(\phi) V(\mu_i)) \\
&amp;= var(g^{-1} (\mathbf{x'_i \beta + z'_i \alpha})) + E(a(\phi)V(g^{-1} (\mathbf{x'_i \beta + z'_i \alpha})))
\end{aligned}
\]</span></p>
<p>Without specific assumption about <span class="math inline">\(g()\)</span> and/or the conditional distribution of <span class="math inline">\(\mathbf{y}\)</span>, this is the most simplified version.</p>
<p><br></p>
<p><strong>Marginal covariance of</strong> <span class="math inline">\(\mathbf{y}\)</span></p>
<p>In a linear mixed model, random effects introduce a dependence among observations which share any random effect in common</p>
<p><span class="math display">\[
\begin{aligned}
cov(y_i, y_j) &amp;= cov_{\alpha}(E(y_i | \mathbf{\alpha}),E(y_j | \mathbf{\alpha})) + E_{\alpha}(cov(y_i, y_j | \mathbf{\alpha})) \\
&amp;= cov(\mu_i, \mu_j) + E(0) \\
&amp;= cov(g^{-1}(\mathbf{x}_i' \beta + \mathbf{z}_i' \mathbf{\alpha}), g^{-1}(\mathbf{x}'_j \beta + \mathbf{z}_j' \mathbf{\alpha}))
\end{aligned}
\]</span></p>
<ul>
<li>Important: conditioning to induce the covariability</li>
</ul>
<p>Example:</p>
<p>Repeated measurements on the subjects. Let <span class="math inline">\(y_{ij}\)</span> be the j-th count taken on the i-th subject.</p>
<p>then, the model is <span class="math inline">\(y_{ij} | \mathbf{\alpha} \sim \text{indep } Pois(\mu_{ij})\)</span>. Here</p>
<p><span class="math display">\[
\log(\mu_{ij}) = \mathbf{x}_{ij}' \beta + \alpha_i 
\]</span></p>
<p>where <span class="math inline">\(\alpha_i \sim iid N(0,\sigma^2_{\alpha})\)</span></p>
<p>which is a log-link with a random patient effect.</p>
<p><br></p>
<div id="estimation-3" class="section level2" number="9.1">
<h2>
<span class="header-section-number">9.1</span> Estimation<a class="anchor" aria-label="anchor" href="#estimation-3"><i class="fas fa-link"></i></a>
</h2>
<p>In linear mixed models, the marginal likelihood for <span class="math inline">\(\mathbf{y}\)</span> is the integration of the random effects from the hierarchical formulation</p>
<p><span class="math display">\[
f(\mathbf{y}) = \int f(\mathbf{y}| \alpha) f(\alpha) d \alpha
\]</span></p>
<p>For linear mixed models, we assumed that the 2 component distributions were Gaussian with linear relationships, which implied the marginal distribution was also linear and Gaussian and allows us to solve this integral analytically.</p>
<p>On the other hand, GLMMs, the distribution for <span class="math inline">\(f(\mathbf{y} | \alpha)\)</span> is not Gaussian in general, and for NLMMs, the functional form between the mean response and the random (and fixed) effects is nonlinear. In both cases, we can’t perform the integral analytically, which means we have to solve it</p>
<ul>
<li><p><a href="nonlinear-and-generalized-linear-mixed-models.html#estimation-by-numerical-integration">numerically</a> and/or</p></li>
<li><p><a href="nonlinear-and-generalized-linear-mixed-models.html#estimation-by-linearization">linearize the inverse link function</a>.</p></li>
</ul>
<div id="estimation-by-numerical-integration" class="section level3" number="9.1.1">
<h3>
<span class="header-section-number">9.1.1</span> Estimation by Numerical Integration<a class="anchor" aria-label="anchor" href="#estimation-by-numerical-integration"><i class="fas fa-link"></i></a>
</h3>
<p>The marginal likelihood is</p>
<p><span class="math display">\[
L(\beta; \mathbf{y}) = \int f(\mathbf{y} | \alpha) f(\alpha) d \alpha
\]</span></p>
<p>Estimation fo the fixed effects requires <span class="math inline">\(\frac{\partial l}{\partial \beta}\)</span>, where <span class="math inline">\(l\)</span> is the log-likelihood</p>
<p>One way to obtain the marginal inference is to numerically integrate out the random effects through</p>
<ul>
<li><p>numerical quadrature</p></li>
<li><p>Laplace approximation</p></li>
<li><p>Monte Carlo methods</p></li>
</ul>
<p>When the dimension of <span class="math inline">\(\mathbf{\alpha}\)</span> is relatively low, this is easy. But when the dimension of <span class="math inline">\(\alpha\)</span> is high, additional approximation is required.</p>
<p><br></p>
</div>
<div id="estimation-by-linearization" class="section level3" number="9.1.2">
<h3>
<span class="header-section-number">9.1.2</span> Estimation by Linearization<a class="anchor" aria-label="anchor" href="#estimation-by-linearization"><i class="fas fa-link"></i></a>
</h3>
<p>Idea: Linearized version of the response (known as working response, or pseudo-response) called <span class="math inline">\(\tilde{y}_i\)</span> and then the conditional mean is</p>
<p><span class="math display">\[
E(\tilde{y}_i | \alpha) = \mathbf{x}_i' \beta + \mathbf{z}_i' \alpha
\]</span></p>
<p>and also estimate <span class="math inline">\(var(\tilde{y}_i | \alpha)\)</span>. then, apply <a href="linear-mixed-models.html#linear-mixed-models">Linear Mixed Models</a> estimation as usual.</p>
<p>The difference is only in how the linearization is done (i.e., how to expand <span class="math inline">\(f(\mathbf{x, \theta, \alpha})\)</span> or the inverse link function</p>
<div id="penalized-quasi-likelihood" class="section level4" number="9.1.2.1">
<h4>
<span class="header-section-number">9.1.2.1</span> Penalized quasi-likelihood<a class="anchor" aria-label="anchor" href="#penalized-quasi-likelihood"><i class="fas fa-link"></i></a>
</h4>
<p>(PQL)</p>
<p>This is the more popular method</p>
<p><span class="math display">\[
\tilde{y}_i^{(k)} = \hat{\eta}_i^{(k-1)} + ( y_i - \hat{\mu}_i^{(k-1)})\frac{d \eta}{d \mu}| \hat{\eta}_i^{(k-1)}
\]</span></p>
<p>where</p>
<ul>
<li><p><span class="math inline">\(\eta_i = g(\mu_i)\)</span> is the linear predictor</p></li>
<li><p>k = iteration of the optimization algorithm</p></li>
</ul>
<p>The algorithm updates <span class="math inline">\(\tilde{y}_i\)</span> after each linear mixed model fit using <span class="math inline">\(E(\tilde{y}_i | \alpha)\)</span> and <span class="math inline">\(var(\tilde{y}_i | \alpha)\)</span></p>
<p>Comments:</p>
<ul>
<li><p>Easy to implement</p></li>
<li><p>Inference is only asymptotically correct due to the linearizaton</p></li>
<li><p>Biased estimates are likely for binomial response with small groups and worst for Bernoulli response. Similarly for Poisson models with small counts. <span class="citation">(<a href="references.html#ref-Faraway_2016" role="doc-biblioref">Faraway 2016</a>)</span></p></li>
<li><p>Hypothesis testing and confidence intervals also have problems.</p></li>
</ul>
<p><br></p>
</div>
<div id="generalized-estimating-equations" class="section level4" number="9.1.2.2">
<h4>
<span class="header-section-number">9.1.2.2</span> Generalized Estimating Equations<a class="anchor" aria-label="anchor" href="#generalized-estimating-equations"><i class="fas fa-link"></i></a>
</h4>
<p>(GEE)</p>
<p>Let a marginal generalized linear model for the mean of y as a function of the predictors, which means we linearize the mean response function and assume a dependent error structure</p>
<p>Example<br>
Binary data:</p>
<p><span class="math display">\[
logit (E(\mathbf{y})) = \mathbf{X} \beta
\]</span></p>
<p>If we assume a “working covariance matrix,” <span class="math inline">\(\mathbf{V}\)</span> the the elements of <span class="math inline">\(\mathbf{y}\)</span>, then the maximum likelihood equations for estimating <span class="math inline">\(\beta\)</span> is</p>
<p><span class="math display">\[
\mathbf{X'V^{-1}y} = \mathbf{X'V^{-1}} E(\mathbf{y})
\]</span></p>
<p>If <span class="math inline">\(\mathbf{V}\)</span> is correct, then unbiased estimating equations</p>
<p>We typically define <span class="math inline">\(\mathbf{V} = \mathbf{I}\)</span>. Solutions to unbiased estimating equation give consistent estimators.</p>
<p>In practice, we assume a covariance structure, and then do a logistic regression, and calculate its large sample variance</p>
<p>Let <span class="math inline">\(y_{ij} , j = 1,..,n_i, i = 1,..,K\)</span> be the j-th measurement on the i-th subject.</p>
<p><span class="math display">\[
\mathbf{y}_i = 
\left(
\begin{array}
{c}
y_{i1} \\
. \\
y_{in_i}
\end{array}
\right)
\]</span></p>
<p>with mean</p>
<p><span class="math display">\[
\mathbf{\mu}_i =
\left(
\begin{array}
{c}
\mu_{i1} \\
. \\
\mu_{in_i}
\end{array}
\right)
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\mathbf{x}_{ij} = 
\left(
\begin{array}
{c}
X_{ij1} \\
. \\
X_{ijp}
\end{array}
\right)
\]</span></p>
<p>Let <span class="math inline">\(\mathbf{V}_i = cov(\mathbf{y}_i)\)</span>, then based on<span class="citation">(<a href="references.html#ref-liang1986" role="doc-biblioref">LIANG and ZEGER 1986</a>)</span> GEE estimates for <span class="math inline">\(\beta\)</span> can be obtained from solving the equation:</p>
<p><span class="math display">\[
S(\beta) = \sum_{i=1}^K \frac{\partial \mathbf{\mu}_i'}{\partial \beta} \mathbf{V}^{-1}(\mathbf{y}_i - \mathbf{\mu}_i) = 0
\]</span></p>
<p>Let <span class="math inline">\(\mathbf{R}_i (\mathbf{c})\)</span> be an <span class="math inline">\(n_i \times n_i\)</span> “working” correlation matrix specified up to some parameters <span class="math inline">\(\mathbf{c}\)</span>. Then, <span class="math inline">\(\mathbf{V}_i = a(\phi) \mathbf{B}_i^{1/2}\mathbf{R}(\mathbf{c}) \mathbf{B}_i^{1/2}\)</span>, where <span class="math inline">\(\mathbf{B}_i\)</span> is an <span class="math inline">\(n_i \times n_i\)</span> diagonal matrix with <span class="math inline">\(V(\mu_{ij})\)</span> on the j-th diagonal</p>
<p>If <span class="math inline">\(\mathbf{R}(\mathbf{c})\)</span> is the true correlation matrix of <span class="math inline">\(\mathbf{y}_i\)</span>, then <span class="math inline">\(\mathbf{V}_i\)</span> is the true covariance matrix</p>
<p>The working correlation matrix must be estimated iteratively by a fitting algorithm:</p>
<ol style="list-style-type: decimal">
<li><p>Compute the initial estimate of <span class="math inline">\(\beta\)</span> (using GLM under the independence assumption)</p></li>
<li><p>Compute the working correlation matrix <span class="math inline">\(\mathbf{R}\)</span> based upon studentized residuals</p></li>
<li><p>Compute the estimate covariance <span class="math inline">\(\hat{\mathbf{V}}_i\)</span></p></li>
<li>
<p>Update <span class="math inline">\(\beta\)</span> according to</p>
<p><span class="math display">\[
\beta_{r+1} = \beta_r + (\sum_{i=1}^K \frac{\partial \mathbf{\mu}'_i}{\partial \beta} \hat{\mathbf{V}}_i^{-1} \frac{\partial \mathbf{\mu}_i}{\partial \beta})
\]</span></p>
</li>
<li><p>Iterate until the algorithm converges</p></li>
</ol>
<p>Note: Inference based on likelihoods is not appropriate because this is not a likelihood estimator</p>
</div>
</div>
<div id="estimation-by-bayesian-hierarchical-models" class="section level3" number="9.1.3">
<h3>
<span class="header-section-number">9.1.3</span> Estimation by Bayesian Hierarchical Models<a class="anchor" aria-label="anchor" href="#estimation-by-bayesian-hierarchical-models"><i class="fas fa-link"></i></a>
</h3>
<p>Bayesian Estimation</p>
<p><span class="math display">\[
f(\mathbf{\alpha}, \mathbf{\beta} | \mathbf{y}) \propto f(\mathbf{y} | \mathbf{\alpha}, \mathbf{\beta}) f(\mathbf{\alpha})f(\mathbf{\beta})
\]</span></p>
<p>Numerical techniques (e.g., MCMC) can be used to find posterior distribution. This method is best in terms of not having to make simplifying approximation and fully accounting for uncertainty in estimation and prediction, but it could be complex, time-consuming, and computationally intensive.</p>
<p>Implementation Issues:</p>
<ul>
<li><p>No valid joint distribution can be constructed from the given conditional model and random parameters</p></li>
<li><p>The mean/ variance relationship and the random effects lead to constraints on the marginal covariance model</p></li>
<li><p>Difficult to fit computationally</p></li>
</ul>
<p><br></p>
<p>2 types of estimation approaches:</p>
<ol style="list-style-type: decimal">
<li>
<p>Approximate the objective function (marginal likelihood) through integral approximation</p>
<ol style="list-style-type: decimal">
<li><p>Laplace methods</p></li>
<li><p>Quadrature methods</p></li>
<li><p>Monte Carlo integration</p></li>
</ol>
</li>
<li><p>Approximate the model (based on Taylor series linearizations)</p></li>
</ol>
<p><br></p>
<p>Packages in R</p>
<ul>
<li><p>GLMM: <code>MASS:glmmPQL</code> <code><a href="https://rdrr.io/pkg/lme4/man/glmer.html">lme4::glmer</a></code> <code>glmmTMB</code></p></li>
<li><p>NLMM: <code><a href="https://rdrr.io/pkg/nlme/man/nlme.html">nlme::nlme</a></code>; <code><a href="https://rdrr.io/pkg/lme4/man/nlmer.html">lme4::nlmer</a></code> <code><a href="https://rdrr.io/pkg/brms/man/brm.html">brms::brm</a></code></p></li>
<li><p>Bayesian: <code>MCMCglmm</code> ; <code>brms:brm</code></p></li>
</ul>
<p><br></p>
<p>Example: Non-Gaussian Repeated measurements</p>
<ul>
<li><p>When the data are Gaussian, then <a href="linear-mixed-models.html#linear-mixed-models">Linear Mixed Models</a></p></li>
<li><p>When the data are non-Gaussian, then <a href="nonlinear-and-generalized-linear-mixed-models.html#nonlinear-and-generalized-linear-mixed-models">Nonlinear and Generalized Linear Mixed Models</a></p></li>
</ul>
</div>
</div>
<div id="application-7" class="section level2" number="9.2">
<h2>
<span class="header-section-number">9.2</span> Application<a class="anchor" aria-label="anchor" href="#application-7"><i class="fas fa-link"></i></a>
</h2>
<div id="binomial-cbpp-data" class="section level3" number="9.2.1">
<h3>
<span class="header-section-number">9.2.1</span> Binomial (CBPP Data)<a class="anchor" aria-label="anchor" href="#binomial-cbpp-data"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb478"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">cbpp</span>,package <span class="op">=</span> <span class="st">"lme4"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">cbpp</span><span class="op">)</span></code></pre></div>
<pre><code>##   herd incidence size period
## 1    1         2   14      1
## 2    1         3   12      2
## 3    1         4    9      3
## 4    1         0    5      4
## 5    2         3   22      1
## 6    2         1   18      2</code></pre>
<p>PQL</p>
<p>Pro:</p>
<ul>
<li><p>Linearizes the response to have a pseudo-response as the mean response (like LMM)</p></li>
<li><p>computationally efficient</p></li>
</ul>
<p>Cons:</p>
<ul>
<li><p>biased for binary, Poisson data with small counts</p></li>
<li><p>random effects have to be interpreted on the link scale</p></li>
<li><p>can’t interpret AIC/BIC value</p></li>
</ul>
<div class="sourceCode" id="cb480"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.stats.ox.ac.uk/pub/MASS4/">MASS</a></span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: package 'MASS' was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb482"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pql_cbpp</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/glmmPQL.html">glmmPQL</a></span><span class="op">(</span>
        <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">incidence</span>, <span class="va">size</span> <span class="op">-</span> <span class="va">incidence</span><span class="op">)</span> <span class="op">~</span> <span class="va">period</span>,
        random <span class="op">=</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">herd</span>,
        data <span class="op">=</span> <span class="va">cbpp</span>,
        family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"logit"</span><span class="op">)</span>,
        verbose <span class="op">=</span> <span class="cn">F</span>
    <span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">pql_cbpp</span><span class="op">)</span></code></pre></div>
<pre><code>## Linear mixed-effects model fit by maximum likelihood
##   Data: cbpp 
##   AIC BIC logLik
##    NA  NA     NA
## 
## Random effects:
##  Formula: ~1 | herd
##         (Intercept) Residual
## StdDev:   0.5563535 1.184527
## 
## Variance function:
##  Structure: fixed weights
##  Formula: ~invwt 
## Fixed effects:  cbind(incidence, size - incidence) ~ period 
##                 Value Std.Error DF   t-value p-value
## (Intercept) -1.327364 0.2390194 38 -5.553372  0.0000
## period2     -1.016126 0.3684079 38 -2.758156  0.0089
## period3     -1.149984 0.3937029 38 -2.920944  0.0058
## period4     -1.605217 0.5178388 38 -3.099839  0.0036
##  Correlation: 
##         (Intr) perid2 perid3
## period2 -0.399              
## period3 -0.373  0.260       
## period4 -0.282  0.196  0.182
## 
## Standardized Within-Group Residuals:
##        Min         Q1        Med         Q3        Max 
## -2.0591168 -0.6493095 -0.2747620  0.5170492  2.6187632 
## 
## Number of Observations: 56
## Number of Groups: 15</code></pre>
<div class="sourceCode" id="cb484"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fl">0.556</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1.743684</code></pre>
<p>is how the herd specific outcome odds varies.</p>
<p>We can interpret the fixed effect coefficients just like in GLM. Because we use logit link function here, we can say that the log odds of the probability of having a case in period 2 is -1.016 less than period 1 (baseline).</p>
<div class="sourceCode" id="cb486"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">pql_cbpp</span><span class="op">)</span><span class="op">$</span><span class="va">tTable</span></code></pre></div>
<pre><code>##                 Value Std.Error DF   t-value      p-value
## (Intercept) -1.327364 0.2390194 38 -5.553372 2.333216e-06
## period2     -1.016126 0.3684079 38 -2.758156 8.888179e-03
## period3     -1.149984 0.3937029 38 -2.920944 5.843007e-03
## period4     -1.605217 0.5178388 38 -3.099839 3.637000e-03</code></pre>
<p>Numerical Integration</p>
<p>Pro:</p>
<ul>
<li>more accurate</li>
</ul>
<p>Con:</p>
<ul>
<li><p>computationally expensive</p></li>
<li><p>won’t work for complex models.</p></li>
</ul>
<div class="sourceCode" id="cb488"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: package 'lme4' was built under R version 4.0.5</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Warning: package 'Matrix' was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb492"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">numint_cbpp</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/glmer.html">glmer</a></span><span class="op">(</span>
        <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">incidence</span>, <span class="va">size</span> <span class="op">-</span> <span class="va">incidence</span><span class="op">)</span> <span class="op">~</span> <span class="va">period</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">herd</span><span class="op">)</span>,
        data <span class="op">=</span> <span class="va">cbpp</span>,
        family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"logit"</span><span class="op">)</span>
    <span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">numint_cbpp</span><span class="op">)</span></code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: cbind(incidence, size - incidence) ~ period + (1 | herd)
##    Data: cbpp
## 
##      AIC      BIC   logLik deviance df.resid 
##    194.1    204.2    -92.0    184.1       51 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.3816 -0.7889 -0.2026  0.5142  2.8791 
## 
## Random effects:
##  Groups Name        Variance Std.Dev.
##  herd   (Intercept) 0.4123   0.6421  
## Number of obs: 56, groups:  herd, 15
## 
## Fixed effects:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -1.3983     0.2312  -6.048 1.47e-09 ***
## period2      -0.9919     0.3032  -3.272 0.001068 ** 
## period3      -1.1282     0.3228  -3.495 0.000474 ***
## period4      -1.5797     0.4220  -3.743 0.000182 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Correlation of Fixed Effects:
##         (Intr) perid2 perid3
## period2 -0.363              
## period3 -0.340  0.280       
## period4 -0.260  0.213  0.198</code></pre>
<p>For small data set, the difference between two approaches are minimal</p>
<div class="sourceCode" id="cb494"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://rbenchmark.googlecode.com">rbenchmark</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/rbenchmark/man/benchmark.html">benchmark</a></span><span class="op">(</span>
    <span class="st">"MASS"</span> <span class="op">=</span> <span class="op">{</span>
        <span class="va">pql_cbpp</span> <span class="op">&lt;-</span>
            <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/glmmPQL.html">glmmPQL</a></span><span class="op">(</span>
                <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">incidence</span>, <span class="va">size</span> <span class="op">-</span> <span class="va">incidence</span><span class="op">)</span> <span class="op">~</span> <span class="va">period</span>,
                random <span class="op">=</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">herd</span>,
                data <span class="op">=</span> <span class="va">cbpp</span>,
                family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"logit"</span><span class="op">)</span>,
                verbose <span class="op">=</span> <span class="cn">F</span>
            <span class="op">)</span>
    <span class="op">}</span>,
    <span class="st">"lme4"</span> <span class="op">=</span> <span class="op">{</span>
        <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/glmer.html">glmer</a></span><span class="op">(</span>
            <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">incidence</span>, <span class="va">size</span> <span class="op">-</span> <span class="va">incidence</span><span class="op">)</span> <span class="op">~</span> <span class="va">period</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">herd</span><span class="op">)</span>,
            data <span class="op">=</span> <span class="va">cbpp</span>,
            family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"logit"</span><span class="op">)</span>
        <span class="op">)</span>
    <span class="op">}</span>,
    replications <span class="op">=</span> <span class="fl">50</span>,
    columns <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"test"</span>, <span class="st">"replications"</span>, <span class="st">"elapsed"</span>, <span class="st">"relative"</span><span class="op">)</span>,
    order <span class="op">=</span> <span class="st">"relative"</span>
<span class="op">)</span></code></pre></div>
<pre><code>##   test replications elapsed relative
## 1 MASS           50    2.62    1.000
## 2 lme4           50    5.30    2.023</code></pre>
<p>In numerical integration, we can set <code>nAGQ &gt; 1</code> to switch the method of likelihood evaluation, which might increase accuracy</p>
<div class="sourceCode" id="cb496"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span>
<span class="va">numint_cbpp_GH</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/glmer.html">glmer</a></span><span class="op">(</span>
        <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">incidence</span>, <span class="va">size</span> <span class="op">-</span> <span class="va">incidence</span><span class="op">)</span> <span class="op">~</span> <span class="va">period</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">herd</span><span class="op">)</span>,
        data <span class="op">=</span> <span class="va">cbpp</span>,
        family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"logit"</span><span class="op">)</span>,
        nAGQ <span class="op">=</span> <span class="fl">20</span>
    <span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">numint_cbpp_GH</span><span class="op">)</span><span class="op">$</span><span class="va">coefficients</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">numint_cbpp</span><span class="op">)</span><span class="op">$</span><span class="va">coefficients</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span></code></pre></div>
<pre><code>##   (Intercept)       period2       period3       period4 
## -0.0008808634  0.0005160912  0.0004066218  0.0002644629</code></pre>
<p>Bayesian approach to GLMMs</p>
<ul>
<li><p>assume the fixed effects parameters have distribution</p></li>
<li><p>can handle models with intractable result under traditional methods</p></li>
<li><p>computationally expensive</p></li>
</ul>
<div class="sourceCode" id="cb498"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">MCMCglmm</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: package 'MCMCglmm' was built under R version 4.0.5</code></pre>
<pre><code>## Loading required package: coda</code></pre>
<pre><code>## Loading required package: ape</code></pre>
<pre><code>## Warning: package 'ape' was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb503"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Bayes_cbpp</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="https://rdrr.io/pkg/MCMCglmm/man/MCMCglmm.html">MCMCglmm</a></span><span class="op">(</span>
        <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">incidence</span>, <span class="va">size</span> <span class="op">-</span> <span class="va">incidence</span><span class="op">)</span> <span class="op">~</span> <span class="va">period</span>,
        random <span class="op">=</span> <span class="op">~</span> <span class="va">herd</span>,
        data <span class="op">=</span> <span class="va">cbpp</span>,
        family <span class="op">=</span> <span class="st">"multinomial2"</span>,
        verbose <span class="op">=</span> <span class="cn">FALSE</span>
    <span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">Bayes_cbpp</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Iterations = 3001:12991
##  Thinning interval  = 10
##  Sample size  = 1000 
## 
##  DIC: 537.7511 
## 
##  G-structure:  ~herd
## 
##      post.mean  l-95% CI  u-95% CI eff.samp
## herd  0.001022 9.579e-17 7.923e-05      287
## 
##  R-structure:  ~units
## 
##       post.mean l-95% CI u-95% CI eff.samp
## units     1.155   0.3415    2.194    363.5
## 
##  Location effects: cbind(incidence, size - incidence) ~ period 
## 
##             post.mean l-95% CI u-95% CI eff.samp  pMCMC    
## (Intercept)   -1.5404  -2.2180  -0.9078    755.1 &lt;0.001 ***
## period2       -1.2751  -2.2910  -0.1619    775.6  0.016 *  
## period3       -1.4065  -2.4474  -0.3088    746.1  0.002 ** 
## period4       -1.9516  -3.2032  -0.6183    704.3  0.002 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<ul>
<li>
<code>MCMCglmm</code> fits a residual variance component (useful with dispersion issues)</li>
</ul>
<div class="sourceCode" id="cb505"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">Bayes_cbpp</span><span class="op">$</span><span class="va">VCV</span>,<span class="fl">2</span>,<span class="va">sd</span><span class="op">)</span> <span class="co">#explains less variability</span></code></pre></div>
<pre><code>##       herd      units 
## 0.01664994 0.52416759</code></pre>
<div class="sourceCode" id="cb507"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">Bayes_cbpp</span><span class="op">)</span><span class="op">$</span><span class="va">solutions</span></code></pre></div>
<pre><code>##             post.mean  l-95% CI   u-95% CI eff.samp pMCMC
## (Intercept) -1.540398 -2.218031 -0.9078279 755.1080 0.001
## period2     -1.275133 -2.291032 -0.1618755 775.6122 0.016
## period3     -1.406450 -2.447372 -0.3087735 746.1049 0.002
## period4     -1.951610 -3.203185 -0.6183007 704.2754 0.002</code></pre>
<p>interpret Bayesian “credible intervals” similarly to confidence intervals</p>
<p>Make sure you make post-hoc diagnoses</p>
<div class="sourceCode" id="cb509"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://lattice.r-forge.r-project.org/">lattice</a></span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: package 'lattice' was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb511"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/coda/man/mcmc.html">as.mcmc</a></span><span class="op">(</span><span class="va">Bayes_cbpp</span><span class="op">$</span><span class="va">Sol</span><span class="op">)</span>, layout <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-nonlinear_generalized_linear_mixed_files/figure-html/unnamed-chunk-11-1.png" width="672"></div>
<p>There is no trend, well-mixed</p>
<div class="sourceCode" id="cb512"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/coda/man/mcmc.html">as.mcmc</a></span><span class="op">(</span><span class="va">Bayes_cbpp</span><span class="op">$</span><span class="va">VCV</span><span class="op">)</span>,layout<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-nonlinear_generalized_linear_mixed_files/figure-html/unnamed-chunk-12-1.png" width="672"></div>
<p>For the herd variable, a lot of them are 0, which suggests problem. To fix the instability in the herd effect sampling, we can either</p>
<ul>
<li><p>modify the prior distribution on the herd variation</p></li>
<li><p>increases the number of iteration</p></li>
</ul>
<div class="sourceCode" id="cb513"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">MCMCglmm</span><span class="op">)</span>
<span class="va">Bayes_cbpp2</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="https://rdrr.io/pkg/MCMCglmm/man/MCMCglmm.html">MCMCglmm</a></span><span class="op">(</span>
        <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">incidence</span>, <span class="va">size</span> <span class="op">-</span> <span class="va">incidence</span><span class="op">)</span> <span class="op">~</span> <span class="va">period</span>,
        random <span class="op">=</span> <span class="op">~</span> <span class="va">herd</span>,
        data <span class="op">=</span> <span class="va">cbpp</span>,
        family <span class="op">=</span> <span class="st">"multinomial2"</span>,
        nitt <span class="op">=</span> <span class="fl">20000</span>,
        burnin <span class="op">=</span> <span class="fl">10000</span>,
        prior <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/gsubfn/man/list.html">list</a></span><span class="op">(</span>G <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/gsubfn/man/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/gsubfn/man/list.html">list</a></span><span class="op">(</span>
            V <span class="op">=</span> <span class="fl">1</span>, nu <span class="op">=</span> <span class="fl">.1</span>
        <span class="op">)</span><span class="op">)</span><span class="op">)</span>,
        verbose <span class="op">=</span> <span class="cn">FALSE</span>
    <span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/coda/man/mcmc.html">as.mcmc</a></span><span class="op">(</span><span class="va">Bayes_cbpp2</span><span class="op">$</span><span class="va">VCV</span><span class="op">)</span>, layout <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-nonlinear_generalized_linear_mixed_files/figure-html/unnamed-chunk-13-1.png" width="672"></div>
<p>To change the shape of priors, in <code>MCMCglmm</code> use:</p>
<ul>
<li><p><code>V</code> controls for the location of the distribution (default = 1)</p></li>
<li><p><code>nu</code> controls for the concentration around V (default = 0)</p></li>
</ul>
<p><br></p>
</div>
<div id="count-owl-data" class="section level3" number="9.2.2">
<h3>
<span class="header-section-number">9.2.2</span> Count (Owl Data)<a class="anchor" aria-label="anchor" href="#count-owl-data"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb514"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/glmmTMB/glmmTMB">glmmTMB</a></span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: package 'glmmTMB' was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb516"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: package 'dplyr' was built under R version 4.0.5</code></pre>
<pre><code>## 
## Attaching package: 'dplyr'</code></pre>
<pre><code>## The following object is masked from 'package:MASS':
## 
##     select</code></pre>
<pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb522"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">Owls</span>, package <span class="op">=</span> <span class="st">"glmmTMB"</span><span class="op">)</span>
<span class="va">Owls</span> <span class="op">&lt;-</span> <span class="va">Owls</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>Ncalls <span class="op">=</span> <span class="va">SiblingNegotiation</span><span class="op">)</span></code></pre></div>
<p>In a typical Poisson model, <span class="math inline">\(\lambda\)</span> (Poisson mean), is model as <span class="math inline">\(\log(\lambda) = \mathbf{x'\beta}\)</span> But if the response is the rate (e.g., counts per BroodSize), we could model it as <span class="math inline">\(\log(\lambda / b) = \mathbf{x'\beta}\)</span> , equivalently <span class="math inline">\(\log(\lambda) = \log(b) + \mathbf{x'\beta}\)</span> where <span class="math inline">\(b\)</span> is BroodSize. Hence, we “offset” the mean by the log of this variable.</p>
<div class="sourceCode" id="cb523"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">owls_glmer</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/glmer.html">glmer</a></span><span class="op">(</span>
        <span class="va">Ncalls</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/stats/offset.html">offset</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">BroodSize</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="va">FoodTreatment</span> <span class="op">*</span> <span class="va">SexParent</span> <span class="op">+</span>
            <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">Nest</span><span class="op">)</span>,
        family <span class="op">=</span> <span class="va">poisson</span>,
        data <span class="op">=</span> <span class="va">Owls</span>
    <span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">owls_glmer</span><span class="op">)</span></code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: poisson  ( log )
## Formula: Ncalls ~ offset(log(BroodSize)) + FoodTreatment * SexParent +  
##     (1 | Nest)
##    Data: Owls
## 
##      AIC      BIC   logLik deviance df.resid 
##   5212.8   5234.8  -2601.4   5202.8      594 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5529 -1.7971 -0.6842  1.2689 11.4312 
## 
## Random effects:
##  Groups Name        Variance Std.Dev.
##  Nest   (Intercept) 0.2063   0.4542  
## Number of obs: 599, groups:  Nest, 27
## 
## Fixed effects:
##                                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                          0.65585    0.09567   6.855 7.12e-12 ***
## FoodTreatmentSatiated               -0.65612    0.05606 -11.705  &lt; 2e-16 ***
## SexParentMale                       -0.03705    0.04501  -0.823   0.4104    
## FoodTreatmentSatiated:SexParentMale  0.13135    0.07036   1.867   0.0619 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Correlation of Fixed Effects:
##             (Intr) FdTrtS SxPrnM
## FdTrtmntStt -0.225              
## SexParentMl -0.292  0.491       
## FdTrtmS:SPM  0.170 -0.768 -0.605</code></pre>
<ul>
<li><p>nest explains a relatively large proportion of the variability (its standard deviation is larger than some coefficients)</p></li>
<li><p>the model fit isn’t great (deviance of 5202 on 594 df)</p></li>
</ul>
<div class="sourceCode" id="cb525"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Negative binomial model</span>
<span class="va">owls_glmerNB</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/glmer.nb.html">glmer.nb</a></span><span class="op">(</span><span class="va">Ncalls</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/stats/offset.html">offset</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">BroodSize</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="va">FoodTreatment</span> <span class="op">*</span> <span class="va">SexParent</span>
             <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">Nest</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">Owls</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>Deviance <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">owls_glmerNB</span><span class="op">)</span><span class="op">$</span><span class="va">AICtab</span><span class="op">[</span><span class="st">"deviance"</span><span class="op">]</span>, <span class="fl">3</span><span class="op">)</span>,
  df <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">owls_glmerNB</span><span class="op">)</span><span class="op">$</span><span class="va">AICtab</span><span class="op">[</span><span class="st">"df.resid"</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<pre><code>## Deviance.deviance       df.df.resid 
##          3483.616           593.000</code></pre>
<p>There is an improvement using negative binomial considering overdispersion</p>
<div class="sourceCode" id="cb527"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">Owls</span><span class="op">$</span><span class="va">Ncalls</span>,breaks<span class="op">=</span><span class="fl">30</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-nonlinear_generalized_linear_mixed_files/figure-html/unnamed-chunk-17-1.png" width="672"></div>
<p>To account for too many 0s in these data, we can use zero-inflated Poisson (ZIP) model.</p>
<ul>
<li>
<code>glmmTMB</code> can handle ZIP GLMMs since it adds automatic differentiation to existing estimation strategies.</li>
</ul>
<div class="sourceCode" id="cb528"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/glmmTMB/glmmTMB">glmmTMB</a></span><span class="op">)</span>
<span class="va">owls_glmm</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="https://rdrr.io/pkg/glmmTMB/man/glmmTMB.html">glmmTMB</a></span><span class="op">(</span>
        <span class="va">Ncalls</span> <span class="op">~</span> <span class="va">FoodTreatment</span> <span class="op">*</span> <span class="va">SexParent</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/offset.html">offset</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">BroodSize</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
            <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">Nest</span><span class="op">)</span>,
        ziformula <span class="op">=</span>  <span class="op">~</span> <span class="fl">0</span>,
        family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/glmmTMB/man/nbinom2.html">nbinom2</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>,
        data <span class="op">=</span> <span class="va">Owls</span>
    <span class="op">)</span>
<span class="va">owls_glmm_zi</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="https://rdrr.io/pkg/glmmTMB/man/glmmTMB.html">glmmTMB</a></span><span class="op">(</span>
        <span class="va">Ncalls</span> <span class="op">~</span> <span class="va">FoodTreatment</span> <span class="op">*</span> <span class="va">SexParent</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/offset.html">offset</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">BroodSize</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
            <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">Nest</span><span class="op">)</span>,
        ziformula <span class="op">=</span>  <span class="op">~</span> <span class="fl">1</span>,
        family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/glmmTMB/man/nbinom2.html">nbinom2</a></span><span class="op">(</span>link
                         <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>,
        data <span class="op">=</span> <span class="va">Owls</span>
    <span class="op">)</span>
<span class="co"># Scale Arrival time to use as a covariate for zero-inflation parameter</span>
<span class="va">Owls</span><span class="op">$</span><span class="va">ArrivalTime</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">Owls</span><span class="op">$</span><span class="va">ArrivalTime</span><span class="op">)</span>
<span class="va">owls_glmm_zi_cov</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/glmmTMB/man/glmmTMB.html">glmmTMB</a></span><span class="op">(</span>
    <span class="va">Ncalls</span> <span class="op">~</span> <span class="va">FoodTreatment</span> <span class="op">*</span> <span class="va">SexParent</span> <span class="op">+</span>
        <span class="fu"><a href="https://rdrr.io/r/stats/offset.html">offset</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">BroodSize</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
        <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">Nest</span><span class="op">)</span>,
    ziformula <span class="op">=</span>  <span class="op">~</span> <span class="va">ArrivalTime</span>,
    family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/glmmTMB/man/nbinom2.html">nbinom2</a></span><span class="op">(</span>link
                     <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>,
    data <span class="op">=</span> <span class="va">Owls</span>
<span class="op">)</span>
<span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/as.matrix.html">as.matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">owls_glmm</span>, <span class="va">owls_glmm_zi</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##              Df      AIC      BIC    logLik deviance    Chisq Chi Df
## owls_glmm     6 3495.610 3521.981 -1741.805 3483.610       NA     NA
## owls_glmm_zi  7 3431.646 3462.413 -1708.823 3417.646 65.96373      1
##                Pr(&gt;Chisq)
## owls_glmm              NA
## owls_glmm_zi 4.592983e-16</code></pre>
<div class="sourceCode" id="cb530"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/as.matrix.html">as.matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">owls_glmm_zi</span>,<span class="va">owls_glmm_zi_cov</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##                  Df      AIC      BIC    logLik deviance    Chisq Chi Df
## owls_glmm_zi      7 3431.646 3462.413 -1708.823 3417.646       NA     NA
## owls_glmm_zi_cov  8 3422.532 3457.694 -1703.266 3406.532 11.11411      1
##                    Pr(&gt;Chisq)
## owls_glmm_zi               NA
## owls_glmm_zi_cov 0.0008567362</code></pre>
<div class="sourceCode" id="cb532"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">owls_glmm_zi_cov</span><span class="op">)</span></code></pre></div>
<pre><code>##  Family: nbinom2  ( log )
## Formula:          
## Ncalls ~ FoodTreatment * SexParent + offset(log(BroodSize)) +      (1 | Nest)
## Zero inflation:          ~ArrivalTime
## Data: Owls
## 
##      AIC      BIC   logLik deviance df.resid 
##   3422.5   3457.7  -1703.3   3406.5      591 
## 
## Random effects:
## 
## Conditional model:
##  Groups Name        Variance Std.Dev.
##  Nest   (Intercept) 0.07487  0.2736  
## Number of obs: 599, groups:  Nest, 27
## 
## Dispersion parameter for nbinom2 family (): 2.22 
## 
## Conditional model:
##                                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                          0.84778    0.09961   8.511  &lt; 2e-16 ***
## FoodTreatmentSatiated               -0.39529    0.13742  -2.877  0.00402 ** 
## SexParentMale                       -0.07025    0.10435  -0.673  0.50079    
## FoodTreatmentSatiated:SexParentMale  0.12388    0.16449   0.753  0.45138    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Zero-inflation model:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -1.3018     0.1261  -10.32  &lt; 2e-16 ***
## ArrivalTime   0.3545     0.1074    3.30 0.000966 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>We can see ZIP GLMM with an arrival time covariate on the zero is best.</p>
<ul>
<li><p>arrival time has a positive effect on observing a nonzero number of calls</p></li>
<li><p>interactions are non significant, the food treatment is significant (fewer calls after eating)</p></li>
<li><p>nest variability is large in magnitude (without this, the parameter estimates change)</p></li>
</ul>
</div>
<div id="binomial-1" class="section level3" number="9.2.3">
<h3>
<span class="header-section-number">9.2.3</span> Binomial<a class="anchor" aria-label="anchor" href="#binomial-1"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb534"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://kwstat.github.io/agridat/">agridat</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: package 'ggplot2' was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb536"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.r-project.org">spaMM</a></span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: package 'spaMM' was built under R version 4.0.5</code></pre>
<pre><code>## Registered S3 methods overwritten by 'registry':
##   method               from 
##   print.registry_field proxy
##   print.registry_entry proxy</code></pre>
<pre><code>## spaMM (Rousset &amp; Ferdy, 2014, version 3.9.0) is loaded.
## Type 'help(spaMM)' for a short introduction,
## 'news(package='spaMM')' for news,
## and 'citation('spaMM')' for proper citation.</code></pre>
<div class="sourceCode" id="cb540"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">gotway.hessianfly</span><span class="op">)</span>
<span class="va">dat</span> <span class="op">&lt;-</span> <span class="va">gotway.hessianfly</span>
<span class="va">dat</span><span class="op">$</span><span class="va">prop</span> <span class="op">&lt;-</span> <span class="va">dat</span><span class="op">$</span><span class="va">y</span> <span class="op">/</span> <span class="va">dat</span><span class="op">$</span><span class="va">n</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">dat</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">lat</span>, y <span class="op">=</span> <span class="va">long</span>, fill <span class="op">=</span> <span class="va">prop</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html">geom_tile</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_fill_gradient</a></span><span class="op">(</span>low <span class="op">=</span> <span class="st">'white'</span>, high <span class="op">=</span> <span class="st">'black'</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_text.html">geom_text</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="va">gen</span>, color <span class="op">=</span> <span class="va">block</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">'Gotway Hessian Fly'</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-nonlinear_generalized_linear_mixed_files/figure-html/unnamed-chunk-19-1.png" width="672"></div>
<ul>
<li><p>Fixed effects (<span class="math inline">\(\beta\)</span>) = genotype</p></li>
<li><p>Random effects (<span class="math inline">\(\alpha\)</span>) = block</p></li>
</ul>
<div class="sourceCode" id="cb541"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">flymodel</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/glmer.html">glmer</a></span><span class="op">(</span>
        <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">n</span> <span class="op">-</span> <span class="va">y</span><span class="op">)</span> <span class="op">~</span> <span class="va">gen</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">block</span><span class="op">)</span>,
        data <span class="op">=</span> <span class="va">dat</span>,
        family <span class="op">=</span> <span class="va">binomial</span>,
        nAGQ <span class="op">=</span> <span class="fl">5</span>
    <span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/spaMM/man/summary.HL.html">summary</a></span><span class="op">(</span><span class="va">flymodel</span><span class="op">)</span></code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Adaptive
##   Gauss-Hermite Quadrature, nAGQ = 5) [glmerMod]
##  Family: binomial  ( logit )
## Formula: cbind(y, n - y) ~ gen + (1 | block)
##    Data: dat
## 
##      AIC      BIC   logLik deviance df.resid 
##    162.2    198.9    -64.1    128.2       47 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -2.38644 -1.01188  0.09631  1.03468  2.75479 
## 
## Random effects:
##  Groups Name        Variance Std.Dev.
##  block  (Intercept) 0.001022 0.03196 
## Number of obs: 64, groups:  block, 4
## 
## Fixed effects:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   1.5035     0.3914   3.841 0.000122 ***
## genG02       -0.1939     0.5302  -0.366 0.714644    
## genG03       -0.5408     0.5103  -1.060 0.289260    
## genG04       -1.4342     0.4714  -3.043 0.002346 ** 
## genG05       -0.2037     0.5429  -0.375 0.707486    
## genG06       -0.9783     0.5046  -1.939 0.052533 .  
## genG07       -0.6041     0.5111  -1.182 0.237235    
## genG08       -1.6774     0.4907  -3.418 0.000630 ***
## genG09       -1.3984     0.4725  -2.960 0.003078 ** 
## genG10       -0.6817     0.5333  -1.278 0.201181    
## genG11       -1.4630     0.4843  -3.021 0.002522 ** 
## genG12       -1.4591     0.4918  -2.967 0.003010 ** 
## genG13       -3.5528     0.6600  -5.383 7.31e-08 ***
## genG14       -2.5073     0.5264  -4.763 1.90e-06 ***
## genG15       -2.0872     0.4851  -4.302 1.69e-05 ***
## genG16       -2.9697     0.5383  -5.517 3.46e-08 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<pre><code>## 
## Correlation matrix not shown by default, as p = 16 &gt; 12.
## Use print(x, correlation=TRUE)  or
##     vcov(x)        if you need it</code></pre>
<p>Equivalently, we can use <code>MCMCglmm</code> , for a Bayesian approach</p>
<div class="sourceCode" id="cb544"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">coda</span><span class="op">)</span>
<span class="va">Bayes_flymodel</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/MCMCglmm/man/MCMCglmm.html">MCMCglmm</a></span><span class="op">(</span>
    <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">n</span> <span class="op">-</span> <span class="va">y</span><span class="op">)</span> <span class="op">~</span> <span class="va">gen</span> ,
    random <span class="op">=</span> <span class="op">~</span> <span class="va">block</span>,
    data <span class="op">=</span> <span class="va">dat</span>,
    family <span class="op">=</span> <span class="st">"multinomial2"</span>,
    verbose <span class="op">=</span> <span class="cn">FALSE</span>
<span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/spaMM/man/plot.HL.html">plot</a></span><span class="op">(</span><span class="va">Bayes_flymodel</span><span class="op">$</span><span class="va">Sol</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, main <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/dimnames.html">dimnames</a></span><span class="op">(</span><span class="va">Bayes_flymodel</span><span class="op">$</span><span class="va">Sol</span><span class="op">)</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-nonlinear_generalized_linear_mixed_files/figure-html/unnamed-chunk-21-1.png" width="672"></div>
<div class="sourceCode" id="cb545"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/coda/man/autocorr.plot.html">autocorr.plot</a></span><span class="op">(</span><span class="va">Bayes_flymodel</span><span class="op">$</span><span class="va">Sol</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>,main<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/dimnames.html">dimnames</a></span><span class="op">(</span><span class="va">Bayes_flymodel</span><span class="op">$</span><span class="va">Sol</span><span class="op">)</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-nonlinear_generalized_linear_mixed_files/figure-html/unnamed-chunk-22-1.png" width="672"></div>
</div>
<div id="example-from-schabenberger_2001-section-8.4.1" class="section level3" number="9.2.4">
<h3>
<span class="header-section-number">9.2.4</span> Example from <span class="citation">(<a href="references.html#ref-Schabenberger_2001" role="doc-biblioref">Schabenberger and Pierce 2001</a>)</span> section 8.4.1<a class="anchor" aria-label="anchor" href="#example-from-schabenberger_2001-section-8.4.1"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb546"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dat2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span><span class="op">(</span><span class="st">"images/YellowPoplarData_r.txt"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">dat2</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'tn'</span>, <span class="st">'k'</span>, <span class="st">'dbh'</span>, <span class="st">'totht'</span>, <span class="st">'dob'</span>, <span class="st">'ht'</span>, <span class="st">'maxd'</span>, <span class="st">'cumv'</span><span class="op">)</span>
<span class="va">dat2</span><span class="op">$</span><span class="va">t</span> <span class="op">&lt;-</span> <span class="va">dat2</span><span class="op">$</span><span class="va">dob</span> <span class="op">/</span> <span class="va">dat2</span><span class="op">$</span><span class="va">dbh</span>
<span class="va">dat2</span><span class="op">$</span><span class="va">r</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="va">dat2</span><span class="op">$</span><span class="va">dob</span> <span class="op">/</span> <span class="va">dat2</span><span class="op">$</span><span class="va">totht</span></code></pre></div>
<p>The cumulative volume relates to the complementary diameter (subplots were created based on total tree height)</p>
<div class="sourceCode" id="cb547"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>
<span class="va">dat2</span> <span class="op">&lt;-</span> <span class="va">dat2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">tn</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>
    z <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span>
        <span class="va">totht</span> <span class="op">&lt;</span> <span class="fl">74</span> <span class="op">&amp;</span> <span class="va">totht</span> <span class="op">&gt;=</span> <span class="fl">0</span> <span class="op">~</span> <span class="st">'a: 0-74ft'</span>,
        <span class="va">totht</span> <span class="op">&lt;</span> <span class="fl">88</span> <span class="op">&amp;</span> <span class="va">totht</span> <span class="op">&gt;=</span> <span class="fl">74</span> <span class="op">~</span> <span class="st">'b: 74-88'</span>,
        <span class="va">totht</span> <span class="op">&lt;</span> <span class="fl">95</span> <span class="op">&amp;</span> <span class="va">totht</span> <span class="op">&gt;=</span> <span class="fl">88</span> <span class="op">~</span> <span class="st">'c: 88-95'</span>,
        <span class="va">totht</span> <span class="op">&lt;</span> <span class="fl">99</span> <span class="op">&amp;</span> <span class="va">totht</span> <span class="op">&gt;=</span> <span class="fl">95</span> <span class="op">~</span> <span class="st">'d: 95-99'</span>,
        <span class="va">totht</span> <span class="op">&lt;</span> <span class="fl">104</span> <span class="op">&amp;</span> <span class="va">totht</span> <span class="op">&gt;=</span> <span class="fl">99</span> <span class="op">~</span> <span class="st">'e: 99-104'</span>,
        <span class="va">totht</span> <span class="op">&lt;</span> <span class="fl">109</span> <span class="op">&amp;</span> <span class="va">totht</span> <span class="op">&gt;=</span> <span class="fl">104</span> <span class="op">~</span> <span class="st">'f: 104-109'</span>,
        <span class="va">totht</span> <span class="op">&lt;</span> <span class="fl">115</span> <span class="op">&amp;</span> <span class="va">totht</span> <span class="op">&gt;=</span> <span class="fl">109</span> <span class="op">~</span> <span class="st">'g: 109-115'</span>,
        <span class="va">totht</span> <span class="op">&lt;</span> <span class="fl">120</span> <span class="op">&amp;</span> <span class="va">totht</span> <span class="op">&gt;=</span> <span class="fl">115</span> <span class="op">~</span> <span class="st">'h: 115-120'</span>,
        <span class="va">totht</span> <span class="op">&lt;</span> <span class="fl">140</span> <span class="op">&amp;</span> <span class="va">totht</span> <span class="op">&gt;=</span> <span class="fl">120</span> <span class="op">~</span> <span class="st">'i: 120-150'</span>,
    <span class="op">)</span>
<span class="op">)</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">dat2</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">r</span>, y <span class="op">=</span> <span class="va">cumv</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/vars.html">vars</a></span><span class="op">(</span><span class="va">z</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-nonlinear_generalized_linear_mixed_files/figure-html/unnamed-chunk-24-1.png" width="672"></div>
<p>The proposed non-linear model:</p>
<p><span class="math display">\[
V_{id_j} = (\beta_0 + (\beta_1 + b_{1i})\frac{D^2_i H_i}{1000})(\exp[-(\beta_2 + b_{2i})t_{ij} \exp(\beta_3 t_{ij})]) + e_{ij}
\]</span></p>
<p>where</p>
<ul>
<li><p><span class="math inline">\(b_{1i}, b_{2i}\)</span> are random effects</p></li>
<li><p><span class="math inline">\(e_{ij}\)</span> are random errors</p></li>
</ul>
<div class="sourceCode" id="cb548"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://svn.r-project.org/R-packages/trunk/nlme/">nlme</a></span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: package 'nlme' was built under R version 4.0.5</code></pre>
<pre><code>## 
## Attaching package: 'nlme'</code></pre>
<pre><code>## The following object is masked from 'package:dplyr':
## 
##     collapse</code></pre>
<pre><code>## The following object is masked from 'package:lme4':
## 
##     lmList</code></pre>
<div class="sourceCode" id="cb553"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tmp</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/nlme.html">nlme</a></span><span class="op">(</span>
        <span class="va">cumv</span> <span class="op">~</span> <span class="op">(</span><span class="va">b0</span> <span class="op">+</span> <span class="op">(</span><span class="va">b1</span> <span class="op">+</span> <span class="va">u1</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="va">dbh</span> <span class="op">*</span> <span class="va">dbh</span> <span class="op">*</span> <span class="va">totht</span> <span class="op">/</span> <span class="fl">1000</span><span class="op">)</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">-</span><span class="op">(</span><span class="va">b2</span> <span class="op">+</span> <span class="va">u2</span><span class="op">)</span> <span class="op">*</span>
                                                                        <span class="op">(</span><span class="va">t</span> <span class="op">/</span> <span class="fl">1000</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">b3</span> <span class="op">*</span> <span class="va">t</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,
        data <span class="op">=</span> <span class="va">dat2</span>,
        fixed <span class="op">=</span> <span class="va">b0</span> <span class="op">+</span> <span class="va">b1</span> <span class="op">+</span> <span class="va">b2</span> <span class="op">+</span> <span class="va">b3</span> <span class="op">~</span> <span class="fl">1</span>,
        <span class="co"># 1 on the right hand side of the formula indicates a single fixed effects for the corresponding parameters</span>
        random <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/gsubfn/man/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/pdDiag.html">pdDiag</a></span><span class="op">(</span><span class="va">u1</span> <span class="op">+</span> <span class="va">u2</span> <span class="op">~</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span>,
        <span class="co">#uncorrelated random effects</span>
        groups <span class="op">=</span> <span class="op">~</span> <span class="va">tn</span>,
        <span class="co">#group on trees so each tree w/ have u1 and u2</span>
        start <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/gsubfn/man/list.html">list</a></span><span class="op">(</span>fixed <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>
            b0 <span class="op">=</span> <span class="fl">0.25</span>,
            b1 <span class="op">=</span> <span class="fl">2.3</span>,
            b2 <span class="op">=</span> <span class="fl">2.87</span>,
            b3 <span class="op">=</span> <span class="fl">6.7</span>
        <span class="op">)</span><span class="op">)</span>
    <span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/spaMM/man/summary.HL.html">summary</a></span><span class="op">(</span><span class="va">tmp</span><span class="op">)</span></code></pre></div>
<pre><code>## Nonlinear mixed-effects model fit by maximum likelihood
##   Model: cumv ~ (b0 + (b1 + u1) * (dbh * dbh * totht/1000)) * (exp(-(b2 +      u2) * (t/1000) * exp(b3 * t))) 
##   Data: dat2 
##        AIC      BIC    logLik
##   31103.73 31151.33 -15544.86
## 
## Random effects:
##  Formula: list(u1 ~ 1, u2 ~ 1)
##  Level: tn
##  Structure: Diagonal
##                u1       u2 Residual
## StdDev: 0.1508094 0.447829 2.226361
## 
## Fixed effects:  b0 + b1 + b2 + b3 ~ 1 
##       Value  Std.Error   DF  t-value p-value
## b0 0.249386 0.12894686 6297   1.9340  0.0532
## b1 2.288832 0.01266805 6297 180.6776  0.0000
## b2 2.500497 0.05606685 6297  44.5985  0.0000
## b3 6.848871 0.02140677 6297 319.9395  0.0000
##  Correlation: 
##    b0     b1     b2    
## b1 -0.639              
## b2  0.054  0.056       
## b3 -0.011 -0.066 -0.850
## 
## Standardized Within-Group Residuals:
##           Min            Q1           Med            Q3           Max 
## -6.694575e+00 -3.081861e-01 -8.910696e-05  3.469469e-01  7.855665e+00 
## 
## Number of Observations: 6636
## Number of Groups: 336</code></pre>
<div class="sourceCode" id="cb555"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">nlme</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/intervals.html">intervals</a></span><span class="op">(</span><span class="va">tmp</span><span class="op">)</span></code></pre></div>
<pre><code>## Approximate 95% confidence intervals
## 
##  Fixed effects:
##           lower      est.     upper
## b0 -0.003318095 0.2493855 0.5020891
## b1  2.264006138 2.2888323 2.3136585
## b2  2.390619987 2.5004970 2.6103740
## b3  6.806919317 6.8488712 6.8908232
## attr(,"label")
## [1] "Fixed effects:"
## 
##  Random Effects:
##   Level: tn 
##            lower      est.     upper
## sd(u1) 0.1376080 0.1508094 0.1652772
## sd(u2) 0.4056135 0.4478290 0.4944382
## 
##  Within-group standard error:
##    lower     est.    upper 
## 2.187260 2.226361 2.266161</code></pre>
<ul>
<li>Little different from the book because of different implementation of nonlinear mixed models.</li>
</ul>
<div class="sourceCode" id="cb557"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://wilkelab.org/cowplot/">cowplot</a></span><span class="op">)</span>
<span class="va">nlmmfn</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">fixed</span>,<span class="va">rand</span>,<span class="va">dbh</span>,<span class="va">totht</span>,<span class="va">t</span><span class="op">)</span><span class="op">{</span>
  <span class="va">b0</span> <span class="op">&lt;-</span> <span class="va">fixed</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>
  <span class="va">b1</span> <span class="op">&lt;-</span> <span class="va">fixed</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>
  <span class="va">b2</span> <span class="op">&lt;-</span> <span class="va">fixed</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>
  <span class="va">b3</span> <span class="op">&lt;-</span> <span class="va">fixed</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span>
  <span class="va">u1</span> <span class="op">&lt;-</span> <span class="va">rand</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>
  <span class="va">u2</span> <span class="op">&lt;-</span> <span class="va">rand</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>
  <span class="co">#just made so we can predict w/o random effects</span>
  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="op">(</span><span class="va">b0</span><span class="op">+</span><span class="op">(</span><span class="va">b1</span><span class="op">+</span><span class="va">u1</span><span class="op">)</span><span class="op">*</span><span class="op">(</span><span class="va">dbh</span><span class="op">*</span><span class="va">dbh</span><span class="op">*</span><span class="va">totht</span><span class="op">/</span><span class="fl">1000</span><span class="op">)</span><span class="op">)</span><span class="op">*</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">-</span><span class="op">(</span><span class="va">b2</span><span class="op">+</span><span class="va">u2</span><span class="op">)</span><span class="op">*</span><span class="op">(</span><span class="va">t</span><span class="op">/</span><span class="fl">1000</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">b3</span><span class="op">*</span><span class="va">t</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="op">}</span>


<span class="co">#Tree 1</span>
<span class="va">pred1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">24</span>,length.out<span class="op">=</span><span class="fl">100</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">pred1</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">'dob'</span>
<span class="va">pred1</span><span class="op">$</span><span class="va">tn</span> <span class="op">&lt;-</span> <span class="fl">1</span>
<span class="va">pred1</span><span class="op">$</span><span class="va">dbh</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span><span class="op">(</span><span class="va">dat2</span><span class="op">[</span><span class="va">dat2</span><span class="op">$</span><span class="va">tn</span><span class="op">==</span><span class="fl">1</span>,<span class="op">]</span><span class="op">$</span><span class="va">dbh</span><span class="op">)</span>
<span class="va">pred1</span><span class="op">$</span><span class="va">t</span> <span class="op">&lt;-</span> <span class="va">pred1</span><span class="op">$</span><span class="va">dob</span><span class="op">/</span><span class="va">pred1</span><span class="op">$</span><span class="va">dbh</span>
<span class="va">pred1</span><span class="op">$</span><span class="va">totht</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span><span class="op">(</span><span class="va">dat2</span><span class="op">[</span><span class="va">dat2</span><span class="op">$</span><span class="va">tn</span><span class="op">==</span><span class="fl">1</span>,<span class="op">]</span><span class="op">$</span><span class="va">totht</span><span class="op">)</span>
<span class="va">pred1</span><span class="op">$</span><span class="va">r</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">-</span><span class="va">pred1</span><span class="op">$</span><span class="va">dob</span><span class="op">/</span><span class="va">pred1</span><span class="op">$</span><span class="va">totht</span>


<span class="va">pred1</span><span class="op">$</span><span class="va">test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/spaMM/man/predict.html">predict</a></span><span class="op">(</span><span class="va">tmp</span>,<span class="va">pred1</span><span class="op">)</span>
<span class="va">pred1</span><span class="op">$</span><span class="va">testno</span> <span class="op">&lt;-</span> <span class="fu">nlmmfn</span><span class="op">(</span>fixed<span class="op">=</span><span class="va">tmp</span><span class="op">$</span><span class="va">coefficients</span><span class="op">$</span><span class="va">fixed</span>, rand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span>,<span class="va">pred1</span><span class="op">$</span><span class="va">dbh</span>,<span class="va">pred1</span><span class="op">$</span><span class="va">totht</span>,<span class="va">pred1</span><span class="op">$</span><span class="va">t</span><span class="op">)</span>

<span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">pred1</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">r</span>,y<span class="op">=</span><span class="va">test</span>,color<span class="op">=</span><span class="st">'with random'</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">r</span>,y<span class="op">=</span><span class="va">testno</span>,color<span class="op">=</span><span class="st">'No random'</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">""</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">dat2</span><span class="op">[</span><span class="va">dat2</span><span class="op">$</span><span class="va">tn</span><span class="op">==</span><span class="fl">1</span>,<span class="op">]</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">r</span>,y<span class="op">=</span><span class="va">cumv</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">'Tree 1'</span><span class="op">)</span><span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span>


<span class="co">#Tree 151</span>
<span class="va">pred151</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">21</span>,length.out<span class="op">=</span><span class="fl">100</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">pred151</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">'dob'</span>
<span class="va">pred151</span><span class="op">$</span><span class="va">tn</span> <span class="op">&lt;-</span> <span class="fl">151</span>
<span class="va">pred151</span><span class="op">$</span><span class="va">dbh</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span><span class="op">(</span><span class="va">dat2</span><span class="op">[</span><span class="va">dat2</span><span class="op">$</span><span class="va">tn</span><span class="op">==</span><span class="fl">151</span>,<span class="op">]</span><span class="op">$</span><span class="va">dbh</span><span class="op">)</span>
<span class="va">pred151</span><span class="op">$</span><span class="va">t</span> <span class="op">&lt;-</span> <span class="va">pred151</span><span class="op">$</span><span class="va">dob</span><span class="op">/</span><span class="va">pred151</span><span class="op">$</span><span class="va">dbh</span>
<span class="va">pred151</span><span class="op">$</span><span class="va">totht</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span><span class="op">(</span><span class="va">dat2</span><span class="op">[</span><span class="va">dat2</span><span class="op">$</span><span class="va">tn</span><span class="op">==</span><span class="fl">151</span>,<span class="op">]</span><span class="op">$</span><span class="va">totht</span><span class="op">)</span>
<span class="va">pred151</span><span class="op">$</span><span class="va">r</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">-</span><span class="va">pred151</span><span class="op">$</span><span class="va">dob</span><span class="op">/</span><span class="va">pred151</span><span class="op">$</span><span class="va">totht</span>


<span class="va">pred151</span><span class="op">$</span><span class="va">test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/spaMM/man/predict.html">predict</a></span><span class="op">(</span><span class="va">tmp</span>,<span class="va">pred151</span><span class="op">)</span>
<span class="va">pred151</span><span class="op">$</span><span class="va">testno</span> <span class="op">&lt;-</span> <span class="fu">nlmmfn</span><span class="op">(</span>fixed<span class="op">=</span><span class="va">tmp</span><span class="op">$</span><span class="va">coefficients</span><span class="op">$</span><span class="va">fixed</span>, rand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span>,<span class="va">pred151</span><span class="op">$</span><span class="va">dbh</span>,<span class="va">pred151</span><span class="op">$</span><span class="va">totht</span>,<span class="va">pred151</span><span class="op">$</span><span class="va">t</span><span class="op">)</span>

<span class="va">p2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">pred151</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">r</span>,y<span class="op">=</span><span class="va">test</span>,color<span class="op">=</span><span class="st">'with random'</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">r</span>,y<span class="op">=</span><span class="va">testno</span>,color<span class="op">=</span><span class="st">'No random'</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">""</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">dat2</span><span class="op">[</span><span class="va">dat2</span><span class="op">$</span><span class="va">tn</span><span class="op">==</span><span class="fl">151</span>,<span class="op">]</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">r</span>,y<span class="op">=</span><span class="va">cumv</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">'Tree 151'</span><span class="op">)</span><span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span>


<span class="co">#Tree 279</span>
<span class="va">pred279</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">9</span>,length.out<span class="op">=</span><span class="fl">100</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">pred279</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">'dob'</span>
<span class="va">pred279</span><span class="op">$</span><span class="va">tn</span> <span class="op">&lt;-</span> <span class="fl">279</span>
<span class="va">pred279</span><span class="op">$</span><span class="va">dbh</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span><span class="op">(</span><span class="va">dat2</span><span class="op">[</span><span class="va">dat2</span><span class="op">$</span><span class="va">tn</span><span class="op">==</span><span class="fl">279</span>,<span class="op">]</span><span class="op">$</span><span class="va">dbh</span><span class="op">)</span>
<span class="va">pred279</span><span class="op">$</span><span class="va">t</span> <span class="op">&lt;-</span> <span class="va">pred279</span><span class="op">$</span><span class="va">dob</span><span class="op">/</span><span class="va">pred279</span><span class="op">$</span><span class="va">dbh</span>
<span class="va">pred279</span><span class="op">$</span><span class="va">totht</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span><span class="op">(</span><span class="va">dat2</span><span class="op">[</span><span class="va">dat2</span><span class="op">$</span><span class="va">tn</span><span class="op">==</span><span class="fl">279</span>,<span class="op">]</span><span class="op">$</span><span class="va">totht</span><span class="op">)</span>
<span class="va">pred279</span><span class="op">$</span><span class="va">r</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">-</span><span class="va">pred279</span><span class="op">$</span><span class="va">dob</span><span class="op">/</span><span class="va">pred279</span><span class="op">$</span><span class="va">totht</span>


<span class="va">pred279</span><span class="op">$</span><span class="va">test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/spaMM/man/predict.html">predict</a></span><span class="op">(</span><span class="va">tmp</span>,<span class="va">pred279</span><span class="op">)</span>
<span class="va">pred279</span><span class="op">$</span><span class="va">testno</span> <span class="op">&lt;-</span> <span class="fu">nlmmfn</span><span class="op">(</span>fixed<span class="op">=</span><span class="va">tmp</span><span class="op">$</span><span class="va">coefficients</span><span class="op">$</span><span class="va">fixed</span>, rand <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span>,<span class="va">pred279</span><span class="op">$</span><span class="va">dbh</span>,<span class="va">pred279</span><span class="op">$</span><span class="va">totht</span>,<span class="va">pred279</span><span class="op">$</span><span class="va">t</span><span class="op">)</span>

<span class="va">p3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">pred279</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">r</span>,y<span class="op">=</span><span class="va">test</span>,color<span class="op">=</span><span class="st">'with random'</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">r</span>,y<span class="op">=</span><span class="va">testno</span>,color<span class="op">=</span><span class="st">'No random'</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">""</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">dat2</span><span class="op">[</span><span class="va">dat2</span><span class="op">$</span><span class="va">tn</span><span class="op">==</span><span class="fl">279</span>,<span class="op">]</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">r</span>,y<span class="op">=</span><span class="va">cumv</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">'Tree 279'</span><span class="op">)</span><span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span>

<span class="fu"><a href="https://wilkelab.org/cowplot/reference/plot_grid.html">plot_grid</a></span><span class="op">(</span><span class="va">p1</span>,<span class="va">p2</span>,<span class="va">p3</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-nonlinear_generalized_linear_mixed_files/figure-html/unnamed-chunk-26-1.png" width="672"></div>
<p>red line = predicted observations based on the common fixed effects</p>
<p>teal line = tree-specific predictions with random effects</p>
</div>
</div>
<div id="summary-1" class="section level2" number="9.3">
<h2>
<span class="header-section-number">9.3</span> Summary<a class="anchor" aria-label="anchor" href="#summary-1"><i class="fas fa-link"></i></a>
</h2>
<div class="inline-figure"><img src="images/umbrella_of_models.PNG" style="display: block; margin: 1em auto"></div>

</div>
</div>



<div class="chapter-nav">
<div class="prev"><a href="linear-mixed-models.html"><span class="header-section-number">8</span> Linear Mixed Models</a></div>
<div class="next"><a href="model-specification.html"><span class="header-section-number">10</span> Model Specification</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#nonlinear-and-generalized-linear-mixed-models"><span class="header-section-number">9</span> Nonlinear and Generalized Linear Mixed Models</a></li>
<li>
<a class="nav-link" href="#estimation-3"><span class="header-section-number">9.1</span> Estimation</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#estimation-by-numerical-integration"><span class="header-section-number">9.1.1</span> Estimation by Numerical Integration</a></li>
<li><a class="nav-link" href="#estimation-by-linearization"><span class="header-section-number">9.1.2</span> Estimation by Linearization</a></li>
<li><a class="nav-link" href="#estimation-by-bayesian-hierarchical-models"><span class="header-section-number">9.1.3</span> Estimation by Bayesian Hierarchical Models</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#application-7"><span class="header-section-number">9.2</span> Application</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#binomial-cbpp-data"><span class="header-section-number">9.2.1</span> Binomial (CBPP Data)</a></li>
<li><a class="nav-link" href="#count-owl-data"><span class="header-section-number">9.2.2</span> Count (Owl Data)</a></li>
<li><a class="nav-link" href="#binomial-1"><span class="header-section-number">9.2.3</span> Binomial</a></li>
<li><a class="nav-link" href="#example-from-schabenberger_2001-section-8.4.1"><span class="header-section-number">9.2.4</span> Example from (Schabenberger and Pierce 2001) section 8.4.1</a></li>
</ul>
</li>
<li><a class="nav-link" href="#summary-1"><span class="header-section-number">9.3</span> Summary</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/mikenguyen13/data_analysis/blob/master/09-nonlinear_generalized_linear_mixed.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/mikenguyen13/data_analysis/edit/master/09-nonlinear_generalized_linear_mixed.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>
</div>
  

  

</div>
 <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>A Guide on Data Analysis</strong>" was written by Mike Nguyen. It was last built on 2021-11-22.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
