# Instrumented Difference-in-differences

Setting: Longitudinal (repeated cross-sectional data) randomized experiment with encouragement to take the treatment regularly after a baseline period [@ye2022instrumented].

Hence, nonparallel trends in outcome may be due to nonparallel trends in exposure if the encouragement has no direct effect on the outcome trend.

Advantages [@ye2022instrumented, p. 4]:

-   Instrumented DID is not affected by time-varying unmeasured confounding in the exposure-outcome relationship because the instrument (encouragement) is independent of time-varying unmeasured confounders.

    -   Unmeasured confounding may be time-invariant but have time-varying effects, or it can be time-varying in the exposure-outcome relationship.

-   Individuals can switch treatment in any direction with instrumented DID, unlike fuzzy DID.

Target estimand: ATE or CATE

Assumptions:

1.  Standard Assumptions:
    1.  SUTVA (consistency): The outcome of an individual is independent of the exposure level of others or the individual's own exposure at another time point.

    2.  Positivity: Everyone has a positive probability of receiving the treatment.

    3.  Random Sampling: Data at each time point is a random sample from the population.
2.  IDID Assumptions [@ye2022instrumented, p. 3]:
    1.  Trend Relevance: The instrument (encouragement) affects the exposure trend for a subpopulation.

    2.  Independence and Exclusion Restriction: Encouragement is unconfounded, has no direct effect on outcome trend, and does not modify treatment effect.

        1.  Advantage over standard IV: Encouragement as an instrument allows for a direct effect on the outcome, as long as it does not affect the outcome trend or modify the treatment effect.

        2.  Example: Suppose a company wants to test the effectiveness of a new pricing strategy on increasing sales of a particular product. However, the company also offers discounts to certain customers who are part of a loyalty program. The discount offered is a potential invalid standard IV as it can have a direct effect on the outcome through increased sales. However, it may still qualify as an instrument for DID if the effect of the pricing strategy varies differently between the loyalty program and non-loyalty program customers over time, but the discount offered to the two groups of customers remains constant over time. These features imply that variables like discounts offered to customers may be more likely to be an instrument for DID, compared to being a standard IV.

    3.  No unmeasured common effect modifier: No unmeasured confounder that affects both the trend in exposure and the trend in the outcome.

    4.  Stable treatment effect over time: CATE does not change over time (more plausible in a short period, and can conduct sensitivity analysis).

Estimation

1.  Wald estimator
2.  Multiply robust estimators: If either the regression-based, inverse probability weighting, or g-estimators are correctly specified, valid inference is guaranteed.

If it is not possible to follow the same individuals throughout the entire panel, we can use a two-sample instrumental variable difference-in-differences approach. In this approach, we observe an exposure dataset and an outcome dataset, which may contain different units. Despite this, we can still calculate the average treatment effect based on summary statistics of the two samples.

```{r, eval = FALSE}
library(devtools)
install_github("tye27/idid")
```
