# Interference

Causal inference is usually assumed without interference from other units (i.e., no spillover effects).

However, this is more like an exception than a norm in social science. So how do we deal with this problem?

Using standard notation for causal inference without interference, we have

-   Potential outcomes: $Y_i(1), Y_i(0)$

-   Observed outcome given your treatment status: $Y_i = Y_i(D_i)$

-   Causal effect: $Y_i(1) - Y_i(0)$

Under interference assumption, we have

-   Potential outcomes: $Y_i(d_1, d_2, \dots, d_n)$

-   Observe outcome given your and everyone's treatment status: $Y_i = Y_i (D_1, D_2, \dots, D_N)$

-   Causal effects can either be

    -   Direct effect $Y_i (D_i = 1, \mathbf{D}_{-i} = \mathbf{d}) - Y_i(D_i = 0, \mathbf{D}_{-i} = \mathbf{d})$

        -   (i.e., your outcome given you are treated and everyone's treatment status minus your outcome given you are untreated and everyone's treatment status)

    -   Spillover effect: $Y_i(D_i = d, \mathbf{D}_{-i} = \mathbf{d}) - Y_i(D_i = d, \mathbf{D}_{-i} = \mathbf{d}')$

        -   (i.e., holding your treatment status constant, what is the difference between outcome when everyone's status is a combination of $\mathbf{d}$ and outcome when everyone's status is not a combination of $\mathbf{d}$)

Under a completely randomized experiment, if we ignore interference, a difference-in-means estimator can still give an unbiased estimate of the average direct effect, because it **averages** everyone's treatment status combinations.

Under cluster randomized experiment, assuming we have only partial interference (i.e., no interference cross clusters), a difference-in-means estimator can give an unbiased estimate for the average total effect: (i.e., sum of the direct and spillover effects).

Two-stage randomized experiments (i.e., randomized treatment assignment to block, and randomized encouragement to receive treatment at the individual level), with partial interference assumption (i.e., no interference across blocks), in this case, you reduce the number of potential values for the other group.

-   Average direct effect = the average of those who were treated - those who were untreated

-   Average spillover effect of encourage = holding your own treatment constant, average the high and low encouragement.

Dependent on the quantity of interest that we choose to use two-stage randomization, whether we are interested in the spillover effect:

1.  Yes -\> two-stage randomization
2.  No
    1.  Only direct effects -\> individual randomization

    2.  Only total effect -\> cluster randomization
