# Spillover

See [@borah2016] for an example in marketing



see [@li2021] for an example in finance

@roche2024proximate for an example in managment 

@elenev2024staggered for healthcare



See @manski1993identification for indiviudal peer effect, can be biased based on endogenous sorting, contextual effects, and other correlated effects

More literature: 
* @moffitt2001policy
* @lee2007identification
* @bramoulle2009identification
* @goldsmith2013social

## Diebold and Yilmaz

* EXPLORING ALL VAR ORDERINGS FOR CALCULATING SPILLOVERS? YES, WE CAN!—A NOTE ON DIEBOLD AND YILMAZ (2009)
* Trans-Atlantic Equity Volatility Connectedness: U.S. and European Financial Institutions, 2004–2014
* On the past, present, and future of the Diebold–Yilmaz approach to dynamic network connectedness
* Measuring Financial Asset Return and Volatility Spillovers, with Application to Global Equity Markets
* Better to give than to receive: Predictive directional measurement of volatility spillovers
* On the network topology of variance decompositions: Measuring the connectedness of financial firms
